### ISSUE TITLE
[JavaScriptアプリケーション]ダウンロード出来ませんでした

### ISSUE THREAD

**Issue by warkene2** [anekos/Ank-Pixiv-Tool#100]
というダイアログのみが出てpixivでダウンロード出来ない場合があります。
例としてhttp://www.pixiv.net/member_illust.php?mode=medium&illust_id=53449215
といった、上下辺のいずれかが2000px以上の作品になるとエラーが出る、気がします。

Firefox42.0
Ank-Pixiv-Tool2.1.1b

**Comment by ginzu** [comment]
当方の環境では正常にダウンロードできましたので、ダウンロード失敗と画像サイズとは直接の関係はないと思われます。
