### ISSUE TITLE
twitterの画像保存と閲覧機能がうまく動作しない

### ISSUE THREAD

**Issue by temydesu** [anekos/Ank-Pixiv-Tool#102]
以前もありましたが個別のツイートのページの画像を保存しようとするとtwitterトップページに飛ばされてしまいます。
また、拡大表示等の閲覧機能も動作しません。

firefoxのバージョンは42.0でAnk-Pixiv-Toolは2.1.1b
です

**Comment by ginzu** [comment]
確認お願いします > 545ab18

**Comment by temydesu** [comment]
正常に作動しました
ありがとうございます
