### ISSUE TITLE
Could it be able to specify different folders for each sites?

### ISSUE THREAD

**Issue by volcksonia** [anekos/Ank-Pixiv-Tool#103]
I use different folders to save pictures. 
I need to change the 'Save illustration to' preference every time i use a different site. 

If it is possible to set different folders or using some tags in 'filename' preference to solve this.

**Comment by ginzu** [comment]
Please try ?site-name? tag .

※refer to wikipage > [Settings/Filename (japanese)](https://github.com/anekos/Ank-Pixiv-Tool/wiki/Ank-Pixiv-Tool-%E8%A8%AD%E5%AE%9A#%E3%82%B5%E3%82%A4%E3%83%88%E3%81%94%E3%81%A8%E3%81%AB%E4%BF%9D%E5%AD%98%E5%85%88%E3%83%95%E3%82%A9%E3%83%AB%E3%83%80%E3%82%92%E5%88%86%E3%81%91%E3%82%8B%E8%A8%AD%E5%AE%9A)

**Comment by volcksonia** [comment]
It works. Thank you.
