### ISSUE TITLE
Not work from AMO

### ISSUE THREAD

**Issue by UdongeinChan** [anekos/Ank-Pixiv-Tool#104]
http://i.imgur.com/l2Rab8G.png

**Comment by ginzu** [comment]
Sorry, please try this commit ＞ 072a1b7

**Comment by UdongeinChan** [comment]
Thanks, work!

Also, in Twitter (Russian interface) work only with «Use current date».

**Comment by ginzu** [comment]
I modified datetime decoder.
Please try this＞ 3f3b069

**Comment by UdongeinChan** [comment]
Good works, thanks.
