### ISSUE TITLE
ここに質問すれば良いのでしょうか？

### ISSUE THREAD

**Issue by HINA-chan** [anekos/Ank-Pixiv-Tool#106]
はじめまして　いつも楽しく愛用させていただいております
さて　今までは画像を保存すると　左上にマークが付いていたのですが
バージョンアップしたら着かなくなってしまいました
付けるにはどこの設定を弄れば良いでしょうか？
教えていただければ幸いでございます

**Comment by HINA-chan** [comment]
質問の仕方がおかしかったですかね？
最新版をインストールするとdownloading.pngを表示してくれないので
どこかにon offスイッチが有るのだろうと思っているのですけどそれがまだ発見出来ないので
教えていただければ幸いです

**Comment by ginzu** [comment]
なにかそんな不具合を作りこんだバージョンがあったような気がします
