### ISSUE TITLE
LAN上のストレージを保存先に指定するとエラーになる

### ISSUE THREAD

**Issue by Qu-chan** [anekos/Ank-Pixiv-Tool#107]
いつもありがたく使わせていただいております。
掲題の件、ローカルの保存先を指定すると問題なく保存できるのですが、
LAN上の外付けHDD内にある共有フォルダを指定すると以下のエラー文を表示して保存できません。

ダウンロード失敗！
Status: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://ankpixiv/content/ankbase.js :: AnkBase.newLocalFile :: line 543"  data: no]

これは本アドオンの仕様で仕方のないことなのでしょうか。
もし可能であれば、次回バージョンアップ時に対応の検討をお願いできませんでしょうか。
以上、よろしくお願いいたします。

**Comment by Qu-chan** [comment]
ダイアログ経由で保存を行うとLAN上のストレージでも保存することができました。
またダイアログ経由であっても、保存先にLAN上の共有フォルダのアドレスを入れておくと同様のエラーを吐きました。

**Comment by anekos** [comment]
設定がまずいということはないのでしょうか。
具体的にどのようにいれていますか。

**Comment by Qu-chan** [comment]
ダイアログ経由で保存を行っても、エラーが出るタイミングが変わるだけで保存はできませんでした。申し訳ありません。

設定というのはFirefoxの設定でしょうか、それとも本アドオンの設定でしょうか。

**Comment by Qu-chan** [comment]
アドオンの設定は以下（レがチェックあり、空白がチェックなし）

◎ダウンロード
　：保存ダイアログを使う		
　：X点以上付けたときダウンロード	
保存ディレクトリ：「LAN上の共有フォルダアドレス」
レ：ダウンロード履歴を保存する
レ：再ダウンロードの確認
レ：再ダウンロードの確認(自動ダウンロード時)
　：中画像クリック時にダウンロード
　：ダウンロード終了時にポップアップ表示
レ：「保存済み」の表示
　：メタテキストの保存
レ：保存済みイラストにマーク付与
　：オリジナルサイズの漫画をダウンロード

◎ファイル名
保存時ファイル名：?illust-id?
代替ファイル名：?illust-id?
　：投稿日時を確認できないときに、現在日時で代替する
　：現在日時で代替したときでも、警告を表示しない

◎ビュアー
　：中サイズ画像クリックで同一タブに大サイズ画像を表示する
「リサイズしない」
　：ウィンドウより小さいときはリサイズしない
100%：ボタンパネルの不透明度の上限
　0%：ボタンパネルの不透明度の下限
     x1：ボタンパネルのサイズ
　：矢印ボタンの戻ると進むを入れ替える
レ：見開きページをひとつの画像として表示する
レ：画像の読込中エフェクトを使用する
　：オリジナルサイズの漫画を表示する

◎その他
　：コメント欄を自動で開く
　：キャプションの続きを自動で開く
レ：サードパーティーCookieを保存する

**Comment by Qu-chan** [comment]
Firefox側の設定は何を書けばいいのかわかりませんが、
「サードパーティCookieの保存」は許可してあります

**Comment by ginzu** [comment]
パス文字の\\→/の変換をやってるせいかもしれませんね。
