### ISSUE TITLE
twitter画像が保存できない。

### ISSUE THREAD

**Issue by temydesu** [anekos/Ank-Pixiv-Tool#109]
個別のツイートのページの画像を保存しようとするとtwitterトップページに飛ばされてしまいます。

firefoxのバージョンは42.0でAnk-Pixiv-Toolは2.1.3です。

**Comment by ncaliber** [comment]
同じく　ブラウザーバージョン44.0.2だけど、ツイッター自体の更新の影響で今までどおり保存ができない

ただ、画像のページを開いた場合、そのツイートの画像をクリックした後に出てくる窓が開いた状態だと保存ができる（ちなみ今までこの方法で保存できなかった）
なお、複数枚があるツイートの場合は一枚ずつでしか保存できない（＝フォルダーで一斉保存ができない）

要すると正常通り保存できない状態です　文法が怪しいかもしれないが参考になれる報告だと嬉しい

**Comment by Jahebi** [comment]
FireFox 44.0.2, Ank-Pixiv-Tool 2.1.3. Twitter images not downloading, Twitter images no longer showing "Already downloaded". Help.

**Comment by UdongeinChan** [comment]
Now need click to image to show and download it.
http://i.imgur.com/IXMJ0cH.png http://i.imgur.com/G35ATvs.png

**Comment by Jahebi** [comment]
What about in cases of Gif/Movie?

**Comment by UdongeinChan** [comment]
It is necessary to fix, including pictures. Just say an option as long as you can download.

**Comment by lentrody** [comment]
Firefox 45.0.1 Ank-Pixiv-Tool 2.1.3

<<ANK<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[NS_ERROR_UNEXPECTED]
  message: 
  filename: undefined
  linenumber: 727
  stack: AnkUtils.createHTMLDocument@chrome://ankpixiv/content/ankutils.js:727:20
AnkPixivModule.prototype.getImageUrlAsync/<@chrome://ankpixiv/content/sites/anktwitter.js:644:21
TaskImpl_run@resource://gre/modules/Task.jsm:315:40
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:1

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
