### ISSUE TITLE
要望:これまでにDLした画像のファイル名から、新たにankpixiv.sqliteを生成

### ISSUE THREAD

**Issue by youpon** [anekos/Ank-Pixiv-Tool#11]
こんにちは。
要望も可能なそうなので、実装してほしいコメント欄の要望をいくつか、メモ的にこちらにも書かせてください。

今までにダウンロードした画像を全て、保存ディレクトリ or 指定したディレクトリに納めて、
Ank Pixiv Toolで、画像をダウンロードした際に付けられるファイル名を指定する「?memoized-name? - ?title? (?illust-id?)」の内の、
「?illust-id?」の部分でその画像のURLを特定し、その情報から新たにankpixiv.sqliteを作る機能が欲しいです。
その画像が削除されてしまっていたり、そもそも投稿者がpixivを退会してしまったりしていた場合は、もしかしたらできないのかもしれませんが…。

**Comment by ginzu** [comment]
webextensionではローカルファイルシステムを操作するAPIがないので実装不可能になりました。
