### ISSUE TITLE
ついっぷるの画像が保存できない

### ISSUE THREAD

**Issue by ncaliber** [anekos/Ank-Pixiv-Tool#110]
ankでついっぷるの画像を保存しようとするとこういうエラーが出てきます
一応Firefox44.0.2

<<ANK<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[Error]
  message: unsupported datetime format = 'Feb 21, 2016 at 09:14 PM JST'
  filename: chrome://ankpixiv/content/ankutils.js
  linenumber: 273
  stack: AnkUtils.decodeDateTimeText@chrome://ankpixiv/content/ankutils.js:273:1
AnkPixivModule/illust.dateTime@chrome://ankpixiv/content/sites/anktwipple.js:143:18
AnkContext/self.info<@chrome://ankpixiv/content/ankcontext.js:30:11
AnkContext@chrome://ankpixiv/content/ankcontext.js:21:18
AnkPixivModule.prototype.downloadCurrentImage/<@chrome://ankpixiv/content/sites/anktwipple.js:319:24
TaskImpl_run@resource://gre/modules/Task.jsm:330:41
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:1

**Comment by ginzu** [comment]
サービスが終了してしまうようですね…。
