### ISSUE TITLE
undefined error

### ISSUE THREAD

**Issue by ninjaworld** [anekos/Ank-Pixiv-Tool#111]
プラグインが死んで使えません。修正もしくは解決方法がありましたら
お教え下さい。また今後アップデートはしないんでしょうか？

Firefox 45.0.1
ank 2.1.3

<<ANK<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[NS_ERROR_UNEXPECTED]
  message: 
  filename: undefined
  linenumber: 727
  stack: AnkUtils.createHTMLDocument@chrome://ankpixiv/content/ankutils.js:727:20
AnkPixivModule.prototype.getImageUrlAsync/</<@chrome://ankpixiv/content/sites/ankpixiv.js:657:21
TaskImpl_run@resource://gre/modules/Task.jsm:315:40
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:1

**Comment by ginzu** [comment]
#116
