### ISSUE TITLE
Cannot download multiple pictures at Firefox 46.0.1

### ISSUE THREAD

**Issue by lcctv** [anekos/Ank-Pixiv-Tool#113]
<<ANK<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[NS_ERROR_UNEXPECTED]
  message: 
  filename: undefined
  linenumber: 727
  stack: AnkUtils.createHTMLDocument@chrome://ankpixiv/content/ankutils.js:727:20
AnkPixivModule.prototype.getImageUrlAsync/</<@chrome://ankpixiv/content/sites/ankpixiv.js:657:21
TaskImpl_run@resource://gre/modules/Task.jsm:315:40
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:11

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by lentrody** [comment]
Disable Autopager

**Comment by lcctv** [comment]
it work! thank you!
