### ISSUE TITLE
サイト毎に保存場所を変えたい

### ISSUE THREAD

**Issue by kanajunn** [anekos/Ank-Pixiv-Tool#114]
保存ディレクトリを固定している場合
pixivなら"設定してある保存先"/pixivみたいな感じに変更できるようにしてほしい

**Comment by ginzu** [comment]
[wiki](https://github.com/anekos/Ank-Pixiv-Tool/wiki/Ank%20Pixiv%20Tool%20%E8%A8%AD%E5%AE%9A)
