### ISSUE TITLE
【要望】ユーザー名更新

### ISSUE THREAD

**Issue by doreddono-to** [anekos/Ank-Pixiv-Tool#115]
Pixivユーザー名の更新機能がほしいです。
イベント等毎にユーザー名にサークル番号等を入れているひとが多いのですがデータベースが古いので保存時に反映されません。
更新を任意にできる機能がほしいです。

**Comment by enoki5150** [comment]
SQLite Managerというアドオンを使えば名前の修正(ankpixiv.sqliteの編集)ができますよ
右上のプロファイルデータベースを選択からankpixiv.sqliteを選択
左にankpixiv.sqliteが表示されたらTablesのmenbersを選択
一覧に出てきたnameを右クリックして編集
名前を変更してOKをクリックです

**Comment by ginzu** [comment]
webextension版にダウンロード履歴／ユーザ情報のインポート機能を作ったので、書き換えたいユーザの情報を書いたjsonファイルを作ってインポートしてやれば上書きが可能になりました。
設定画面等に個別のユーザ検索/更新用UIをつくるのは面倒なのでパスさせてください。

jsonファイルの書式は [これ](https://github.com/anekos/Ank-Pixiv-Tool/blob/feature/webextensions/webextensions/misc/dump_ankpixiv_sqlite.py) でankpixiv.sqliteをダンプして確かめてください。
