### ISSUE TITLE
[Pixiv] 「閉じる」が無効化された

### ISSUE THREAD

**Issue by winiah** [anekos/Ank-Pixiv-Tool#123]
Pixiv 側の変更のせいなので、一応お知らせ致します。

本来なら、イラストもマンガも問わずに、ラスト１枚をクリックすると、Ank ビューアが閉じるハズだが、今日（2017.01.30）で確認してみたら、その機能（および同機能の操作）が異常に作動して、必ず最初の１枚に戻ることによって、ビューアを閉じるのは、ページリロードのみが可能となる。

**Comment by temydesu** [comment]
自分も今日になって同じ状態になりました
Firefoxは51.0.1でAnkPixivは2.1.3です

**Comment by temydesu** [comment]
Firefoxを50.1.0にしたら正常に動作しました。

**Comment by rfhewsgjhug** [comment]
ankviewer.js
519行目のimgCtrl(e => e.addEventListener('error', loadError, true));をコメントアウトすると回避できます。
ビューアを閉じた瞬間に「//画像の読み込みに失敗した」の処理が動いて再表示しているようだ。

**Comment by ginzu** [comment]
ビューアを直す気力がないのでOFFでおねがいします…。
