### ISSUE TITLE
Download list does not persist across restarts

### ISSUE THREAD

**Issue by KaiHD** [anekos/Ank-Pixiv-Tool#124]
Hi there.

I was using the Pixiv Tool and had ~100 downloads queued up, when my Firefox suddenly quit. When it restarted, the Tool wasn't downloading anything.

Could you make the Tool remember the Download list in the next update, please?

**Comment by ginzu** [comment]
リスタート時に同じダウンロードを自動でやりなおす処理を入れるのには抵抗があります。
そのダウンロード処理がサーバに迷惑をかけている可能性があるためです。
