### ISSUE TITLE
nijieの複数枚投稿ファイルダウンロード時、２ページ目以降がサムネイル状態となる

### ISSUE THREAD

**Issue by exitixe** [anekos/Ank-Pixiv-Tool#125]
中画像クリック時に大サイズ画像を表示するオプションを有効としていると、１ページ目は正常だが
２ページ目以降がサムネイル（小さい画像）状態となってしまう。
ダウンロードをすると、表示されているのと同様に１ページ目のみ正常な画像、２ページ目以降サムネイル状態で保存される。
なお、単数枚投稿ファイルについては問題なく表示・保存が可能。
Firefox52.0.1　Ank-pixiv-tool2.1.3

**Comment by ginzu** [comment]
merged. 3dd9d18d185704cc3e88d803ac6654ce3dc25882
