### ISSUE TITLE
Pixivで漫画形式の画像がダウンロード出来ない

### ISSUE THREAD

**Issue by nmt-ms** [anekos/Ank-Pixiv-Tool#126]
Pixivの複数枚投稿形式の画像をダウンロードしようとした場合
画像を見つけられませんでした
という表示のjavaScriptアプリケーションのポップアップが出てダウンロードすることが出来ません。

Firefox 52.0.1
Ank Pixiv Tool 2.1.3

**Comment by kknine99** [comment]
I had the same problem about an hour ago, but it's ok right now.

**Comment by Rinjin28gou** [comment]
私も同様の現象が発生しています。
Firefox51.0以降から発生し始めているようです。

**Comment by SWN-002** [comment]
Same problem when I check the box "Download original size Manga."

Firefox 52.1.0
Ank Pixiv Tool 2.1.3

**Comment by ginzu** [comment]
今は大丈夫かも。
