### ISSUE TITLE
要望:既に保存済みの、「同一の投稿者なんだけど投稿者名がバラバラ」な画像達の、投稿者名を統一する機能

### ISSUE THREAD

**Issue by youpon** [anekos/Ank-Pixiv-Tool#13]
この機能についてですが、特にコミケ等が近付いた際に多いのですが、
投稿者名の後に「@け-23」とか付けるため、頻繁に投稿者名が変わる人が多く、
他にも、全然違う名前に変わる人もいるため、
保存された画像の投稿者名がバラバラになってしまって整理しにくいので、
…この機能はankpixiv.sqliteに投稿者IDも記録されてると云う前提での話になるんじゃないかと思いますが…、
ankpixiv.sqlite内のその情報を参照して、保存ディレクトリ or 指定したディレクトリ内の画像の、同一投稿者による画像の投稿者名の部分を、投稿者ID or 最古 or 最新の投稿者名等に、一括で統一できる機能が欲しいです。

最初から、「?memoized-name?」ではなく「?memoized-id?」にしてれば、こんな事で悩まなくて良かったのですが…、
最初の頃はその辺の設定がよくわからず、使い始めてだいぶ経ってから気になりだしてしまったので…。

複数の要望になってしまい、多いので申し訳無いのですが、よろしくお願いします。

**Comment by enoki5150** [comment]
SQLite Managerというアドオンを使えば名前の修正(ankpixiv.sqliteの編集)ができますよ
右上のプロファイルデータベースを選択からankpixiv.sqliteを選択
左にankpixiv.sqliteが表示されたらTablesのmenbersを選択
一覧に出てきたnameを右クリックして編集
名前を変更してOKをクリックです

**Comment by youpon** [comment]
やってみましたが、やはりそれはankpixiv.sqliteをいじれるだけであって、
肝心の、これまで保存した画像には全く影響しないため、
何の解決にもならないようです…。

**Comment by ginzu** [comment]
webextensionに移行したらローカルファイルは保存ができるだけでリネームも削除もできなくなるので非対応ということで。

**Comment by youpon** [comment]
webextensionって何だろう？と思って検索してみましたが、
http://japanese.engadget.com/2015/08/24/firefox-api-webextension-chrome-and/
これですか。
要約すると、WebExtensionとは、アドオンの製作・動作に使われている仕組みで、
これまでと違って制限が多くなり、アドオン開発者からの評判は悪いけど、
それでもChromeとかSafariとかOperaとかで使われているので、互換性の為にFirefoxも導入する事になってしまったんですね…。
