### ISSUE TITLE
Twitter images not downloading

### ISSUE THREAD

**Issue by chtw31** [anekos/Ank-Pixiv-Tool#130]
Hi there,
Yesterday, Twitter's images can't download, Ank-Pixiv-Tool can't work.
Please help

FireFox 53.0.3, Ank-Pixiv-Tool 2.1.3

**Comment by ginzu** [comment]
修正しました。ビデオのダウンロードはできなくなりました(GIFには対応)
fixed. but video download function has been deprecated 473810b1474c27fcde81b71c2f170361728625a6
