### ISSUE TITLE
Firefox54.0.1にて、最新版に更新できない

### ISSUE THREAD

**Issue by frolex98** [anekos/Ank-Pixiv-Tool#131]
最新版のzipをダウンロード、解凍したのち./source/ディレクトリ以下を再度圧縮し.xpiにリネームしてD&Dという一連の手順を実行しましたが、
Firefoxの現行最新版(54.0.1 x64)では「未検証のためインストールできません」と言われてしまいます。
署名がないということなので私家版として署名を取ろうとしましたが、「Webextensionではないので認証できない」と言われます。
firefoxを強引にダウングレードしてインストールする方法も試し、46.0に戻して実行しましたが、その後最新版にしたら今度は強制的に無効化されてしまいました（結果、それまで動いてた古いバージョンを捨てることに…）。

issue#123,#125に対応したバージョンを現環境で使う方法がわかりません。どなたか教えていただければ幸いです。

**Comment by ginzu** [comment]
#132
