### ISSUE TITLE
Tool can't download pixiv images?

### ISSUE THREAD

**Issue by tonyz723** [anekos/Ank-Pixiv-Tool#132]
It might be due to a change to pixiv somewhere.

When trying to download an image on Pixiv, pressing the icon causes Pixiv to go to the home page. The image does not get downloaded.

**Comment by enoki5150** [comment]
たしかに昼から突然画像保存できなくなりましたね
57以降は対応してない拡張は使えなくなるので新バージョン出して欲しいです

**Comment by ginzu** [comment]
試してみてください。
please try https://github.com/anekos/Ank-Pixiv-Tool/commit/85b8e02922e068ee7376d6ad7c659c0fe44c7154

**Comment by fujiooji** [comment]
>ginzuさん　更新ありがとうございます。
インストールしようとしたのですが、
野良でxpiにしたものは署名が無いという理由で弾かれてしまうのようで、
これはFirefoxをだいぶ前のバージョンに落とすか、何か他に該当箇所の書き換え方法があるのでしょうか？
最新verでは未署名のxpiは開発版やNightlyでも拒否されるようです。（Firefox ver55.0 64bit）

**Comment by enoki5150** [comment]
このアドオンは未検証のためインストール出来ませんと出たんですが・・・

**Comment by temydesu** [comment]
また保存できるようになりました。ありがとうございます。
ですが保存する際に作家名が反映されなくなりました。どうすればいいのでしょうか？
Firefox ESR 52.3.0 64bit

**Comment by yuhkan** [comment]
&gt;  fujiooji  さん

インストールの署名そのものは、"Add-ons for Firefox"のページから、
自己署名する手段が存在しています。
https://blog.halpas.com/archives/8387

しかし、残念ながら今のverでは、チェック段階で
「Starting with Firefox 53, new add-ons on this site can only be WebExtensions.」
と最初からエラーではじかれます。
webextensions対応がされていないという話だったので、姑息的手段で通そうとしてみたところ、
以下の箇所でSyntaxErrorによりはじかれてしまいました。
chrome/content/sites/ankdeviantart.js 行: 364 列: 27
chrome/content/sites/ankimgly.js 行: 269 列: 28
chrome/content/sites/anknijie.js 行: 345 列: 27
chrome/content/sites/anktinami.js 行: 319 列: 28
chrome/content/sites/anktumblr.js 行: 365 列: 28
chrome/content/sites/anktwipple.js 行: 313 列: 28
chrome/content/sites/anktwitpic.js 行: 296 列: 28
chrome/content/ankviewer.js 行: 98 列: 20
chrome/content/sites/anknicosei.js 行: 377 列: 27
chrome/content/sites/anktwitter.js 行: 575 列: 27
chrome/content/sites/ankpixiv.js 行: 511 列: 27
test/storage.js 行: 123 列: 52
chrome/content/ankbase.js 行: 821 列: 15
ちょっと、即座の対応では難しそうな予感が。

**Comment by fujiooji** [comment]
＞yuhkanさん
まさしく仰る通り、その方法で比較的新しいverで使用出来ており、
8月11日にFirefox55.0にうっかり更新した後も無効化を回避し使えていました。
勝手に署名する形なのでここで言ってよいものか、と伏せていました。
が、本日のPixivのサイトデザインの変更に伴い、
どうやらver47.0にまでダウンさせないと自動無効化を避けられない状況になってしまったようです。

個人での解決は正直難しいのですが、
上でも言っておられる方がいるように大きな更新が控えてるため、
ver57.0以降どうなさるかまで保留されるのが良いのではとも個人的には思っています。
長く使わせてもらっていて、Ank以上に保存機能が高いものもないので、
ぜひにご対応くだされば幸いなのですが、こればかりは開発者の方に願うばかりです。

**Comment by moimoifinland** [comment]
>ginzuさん
ファイル保存時にファイル名に使うイラストの投稿者名やタグの自動取得ができなくなっていました。
ankpixiv.jsの129行目、141行目のCSSセレクタを書き換えたら取得できるようになりましたが、自分はpush権限がないので代わりに対応出来ましたらお願いします。

**Comment by gnarf1975** [comment]
Download an image on Pixiv. I´m pressing the icon causes Pixiv to go to the home page. The image does not get downloaded.- I´m a normal user, have no experience in programming. Need a proper Bugfix.

Firefox 55.0.2 X64

**Comment by Denxillia** [comment]
@temydesu 
Try changing the line 
`return query('.profile-unit > a > .user');`
 to 
`return query('.profile .user-name');`

**Comment by LucionGid** [comment]
＞Denxillia

Thank you for your suggestion. However, i still cannot get the author's ID, so which line should be changed?

**Comment by zel3** [comment]
みんなが何をどうやって解決しているのかわからないのですが詳しく教えてもらえませんか

**Comment by Denxillia** [comment]
@LucionGid You can change the line
`return query('.profile-unit > a.user-link');`
to 
`return query('.profile ._user-icon');`
then 😊.

**Comment by temydesu** [comment]
@Denxillia 
作者名の取得ができました。
ありがとうございます。

**Comment by LucionGid** [comment]
>Denxillia

Thank you so much, it works. I do not know much about these java and xml things and thus, was unable to fix it myself. 

>gnarf1975
> zel3
As for the way to update the extension whenever the author makes changes in github, i have just written a step-by-step guide which can be found here: https://pastebin.com/W6zpVGvm
I agree that it is very difficult for a normal user to figure out these steps his/herself. I also find that there is currently no user-friendly guide to solve such issue. Thus, i hope that my guide would be somewhat useful for non-technical users (which are the majority of Internet users).

**Comment by ginzu** [comment]
ユーザ名の件修正しました
fixed: user name problem https://github.com/anekos/Ank-Pixiv-Tool/commit/19123f12f48ed9c167f0c513ee2ed5c16d374a1a

**Comment by enoki5150** [comment]
やっぱこのアドオンは未検証のためインストール出来ませんと出るんですがどうやってインストールすればいいんですか？

**Comment by gnarf1975** [comment]
Can someone just upload the modified xpi-File here? Doesn´t work for me, and i´m getting borded. Thanks.

**Comment by Denxillia** [comment]
^ About the mod xpi file, you can pack one easily by following these steps:
1. Download the source folder
2. Zip all files IN the source folder (not zip the source folder)
3. Change .zip to .xpi

**Comment by moimoifinland** [comment]
修正ありがとうございます。

**Comment by zel3** [comment]
すみませんが皆さんがどんなソフトを使ってどういう操作をしているのかをおしえてもらえませんか？

**Comment by mignonette** [comment]
@Denxillia  I tried your suggestion, but Firefox gives me a pop-up that says it cannot install because it "has not been verified". Does the .xpi file need to be a specific name? I tried "Ank-Pixiv-Tool.xpi" for example.

**Comment by enoki5150** [comment]
いつものように
https://github.com/anekos/Ank-Pixiv-Tool/archive/master.zip
からダウンロードして解凍、sourceフォルダの中身の
chrome
defaults
test
chrome.manifest
install.rdf
Makefile

をzipに圧縮して拡張子をxpiに変更ではインストール出来ません

Firefoxのバージョンは55.0.2です
みなさん特殊なFirefoxでも使ってるんでしょうか？

**Comment by yuhkan** [comment]
&gt; 今来たの方々へ
・Firefox で動かす場合、 Ver47.0以前のものでないと、動作しません。
　When running with Firefox, it will not work unless it is Ver47.0 or earlier.
・現在の最新版Firefox(55.0)では、署名が要求されるため、配布のソースをもとに個人で使う場合は自己署名を行う必要があります
　Currently the latest version of Firefox (55.0) requires a signature, so if you use it for personal use you need to self-sign
・ただし、現在のAnk-pixivは、"Addons for Firefox"で、署名実施をを拒否されます。
　これは、このadd-onが古いアーキティクチャに依存するためです。
　However, the current Ank-pixiv is "Addons for Firefox" and will be refused signature implementation.
　This is because this add - on depends on the old architecture.
・もし署名の問題をクリアしても、Firefox Ver 58.0以降は、古いアーキティクチャのAdd-onは利用できません。
　Even if you clear the problem of signature, Firefox Ver 58.0 and later can not use Add-on of old architecture.
・当面の解決策は、nightly バージョン(署名が不要です)を利用することです
 The immediate solution is to use the nightly version (signature is unnecessary)

より細かい理由については、各自ググってください
For more detailed reasons, please search by yourself.

英文が変な時は、"google翻訳"に文句を言ってください :)
When English sentence is strange, please complain about "google translation" :)

**Comment by enoki5150** [comment]
yuhkan-san Thank you
当面はポータブル版の４６をank pixiv tool専用にします

**Comment by enoki5150** [comment]
yuhkanさん

nightlyバージョンでも弾かれてしまうんですがnightlyバージョンの47以前じゃないとダメなんでしょうか？

**Comment by yuhkan** [comment]
&gt; enoki5150 さん
申し訳ないです、事前情報からの確認のため、実動作についてはチェックしていません。
(55.x相当なら動作するはずなのですが)

**Comment by enoki5150** [comment]
yuhkanさん
こちらこそお手数かけてもうしわけありません
けっきょくFirefox Portable42をank pixiv tool専用にして様子見することにしました
正式リリース版は57以降のこともあって難しいんでしょうか？

**Comment by Barafag** [comment]
> @Denxillia I tried your suggestion, but Firefox gives me a pop-up that says it cannot install because it "has not been verified". Does the .xpi file need to be a specific name? I tried "Ank-Pixiv-Tool.xpi" for example.

What version of FF you use?
You need to install firefox dev or nightly(they still support old addons, but this can change soon.)
FF dev brings you more issues; it'll create separate profile and will use it by default(more pain for inexperienced users: https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles), and even there unsigned addons need some attention: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct  and https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/

Or you can use some older version of FF.

Also, .xpi not needed (in dev and nightly at leat), Just folder would do. A lot easier to modify files...

**Comment by kknine99** [comment]
No need to use older version of firefox, using Firefox ESR instead.
1. Download Firefox ESR from [here](https://www.mozilla.org/en-US/firefox/organizations/all/) , and install it. The lastest version is 52.3.0.
2. Go to "about:config" (Type "about:config" in the address bar and press enter, then click the only button you see).
3. Navigate to "xpinstall.signatures.required", change the value to "false".
4. Restart Firefox. Now the Firefox should accept non-singed extensions.

And Firefox ESR will only get security updates, so it is expected that these legacy extensions should still be available until the end of the Firefox ESR 52.x support period (until June 28, 2018).

**Comment by kine1192** [comment]
Firefox45.9.0 ESR　をこの度Pixiv専用ブラウザとしてアドオンからDLし直して設定してみたところ、漫画形式の画像をDLしようとした際にエラーが発生してDLできませんでした。下記がそのエラー文になります。

<<ANK<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[NS_ERROR_UNEXPECTED]
  message: 
  filename: undefined
  linenumber: 727
  stack: AnkUtils.createHTMLDocument@chrome://ankpixiv/content/ankutils.js:727:20
AnkPixivModule.prototype.getImageUrlAsync/</<@chrome://ankpixiv/content/sites/ankpixiv.js:653:21
TaskImpl_run@resource://gre/modules/Task.jsm:315:40
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:1

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

どなたか対処法を教えていただけないでしょうか？ちなみに複数形式ではない画像は問題なくDLできました。

よろしくお願いします。

**Comment by enoki5150** [comment]
やはりバージョンを下げるしか無いじゃないんでしょうか？４２まで下げれば漫画も落とせます

あと以前コミケ等が近付いたときに投稿者名の後に「C23」とかつけてHNが変わったり完全に変える人のHNを統一する機能ですがSQLite Managerというアドオンを使って名前の修正(ankpixiv.sqliteの編集)ができます

右上のプロファイルデータベースを選択からankpixiv.sqliteを選択
左にankpixiv.sqliteが表示されたらTablesのmenbersを選択
一覧に出てきたnameを右クリックして編集
名前を変更してOKをクリックです

すでに保存してしまった画像についてはFlexible Renamerというフリーソフトで文字列置き換えをすればいいと思います
またマンガ形式のファイルの01,02と言った数字にフォルダ名を先頭に追加を選べば、作者名 - イラスト名 01といったふうにもリネームできるのでおすすめです

**Comment by kine1192** [comment]
Firefox を42.0で入れ直してみたら問題なく落とせました。ありがとうございました！

**Comment by pekeko** [comment]
FireFoxのバージョン落としてもダメでした・・・・・・。

xpiの変換はwindowsでも問題ないですよね？
なぜか、「このアドオンは壊れているため、インストールできませんでした。」となってしまいます。
原因等わかる方がいらっしゃいましたらご教示頂けますでしょうか。

**Comment by pekeko** [comment]
FireFox42.0にしてxpiの変換をやり直したら動きました！
知識不足によりご迷惑をおかけしてすみません・・・。

**Comment by Miamikicchi** [comment]
署名の話ですが、制作者がこれに関して現時点で何らかの行動を取る予定でしょうか。この修正は署名せずに正式に機能しないですので、署名すべきではないかと思います。

それとも、これはyuhkanさんの言っていたように、現時点では問題があって署名できない状態となっているでしょうか。

協力が必要のであれば、私から進んで署名の手続きを行っても構いません。私も、このアドンを沢山の方に使って頂くべく、簡単に使えるようにしたいのです。そうするには、署名が必須になった今は、やはり署名するしかないように見えます。

**Comment by Freezorg** [comment]
@LucionGid I tried following your pastebin as best I could, but when the time comes to add the .xpi to Firefox Dev, it rejects it with the message "This addon could not be installed because it appears to be damaged". I did everything, including disabling the checking of the signatures, and it's not a particularly complicated process, so what could be causing this? Does the version of Firefox Dev have anything to do with this? I am on Firefox Developer Edition 56.0b6.

**Comment by Rocky-3** [comment]
Can 'Anekos' update the addon on Firefox's addon site [here](https://addons.mozilla.org/en-US/firefox/addon/ank-pixiv-tool/)? Since its using legacy apis I cant even upload it for private use, and through the site seems to be the only way to get it signed.

**Comment by LucionGid** [comment]
@Freezorg Maybe that is due to

1) You forgot to delete the META-INF folder before compressing
2) You use some other compression software that does not employ the "Deflate" compression method

**Comment by Freezorg** [comment]
@LucionGid Nope, I made sure to follow that step too, and also use 7zip with the "deflate" compression method, saved as .zip then renamed to .xpi.

**Comment by Freezorg** [comment]
@LucionGid Nope, I made sure to follow that step too, and also use 7zip with the "deflate" compression method, saved as .zip then renamed to .xpi.

**Comment by LucionGid** [comment]
@Freezorg That's weird. I am on the same version as you and have no issue installing the xpi file at all. When you compress the addon, make sure to compress the necessary files/folders directly. For example, when you first open your newly compressed zip file, you should immediately see the following contents: "chrome" and "defaults" folders, "chrome.manifest" and "install.rdf" files, not some intermediate folder that contains all of these previously mentioned contents. Firefox cannot read through the intermediate folder(s).

**Comment by yuhkan** [comment]
&gt;  Miamikicchi さん
署名不具合の件ですが、先述の手順によって再度試行したところ、通過することを確認しました。
『個人で使う分には』それで問題ないと思いますが、配布を視野に入れる場合、それによって発生しうる
問題の責任所在とか(署名を入れるというのはそういうことですから)を考えた場合、【熟慮】が求められると思います。
(ディスクレイマー条項があればよい、では済まないのは各種事例を挙げるまでもないかと思います)

また、どちらにしても58以降を視野に入れてなにがしかやらないといけないのは変わりません。

**Comment by bokodeko** [comment]
お世話になります。
Firefox42にして再び使えるようになりました。

「タグ検索」をした場合、こちらも仕様が変更されていて、「保存済み」を示す「ピンクの背景」が表示されなくなってかなり経過しています（以前は横5でしたが、今は横4になっています。ちなみに作品画面では「保存済み／使用済み」の赤文字は出ていますが）。

あと、早期に公式更新をお願いします。Firefoxも55まで出ており、Ank-Pixiv-Toolを正常化するのに10以上も前のFirefoxに戻さなければならないというのもなにかしらスッキリしません。
月も改まったというのもありますので、早期に（最新版Firefoxでも対応化のものに）公式更新をお願い致します。

**Comment by Miamikicchi** [comment]
For those not interested in downgrading Firefox, there is the possibility of Nightly builds, the Developer Edition, or the Unbranded builds, which let you disable the signing requirement. There is a possibility this addon will not be signed for now because it uses legacy API and will need a big update for that anyway.

More info: https://wiki.mozilla.org/Add-ons/Extension_Signing#FAQ

英語が大丈夫な方はNightlyかDeveloper EditionあるいはUnbranded builds（無印？）を使うという手もあります。これらのバージョンでは署名強制を解除できます（勿論すべて自己責任でですが）。個人的には無印の方を考えています。

> yuhkan さん
58以降は使えなくなる状況でしたか。でしたら、今の所は署名の話から降ります。参考になりました。

**Comment by unthinking** [comment]
cyberfox 52.3でもank pixiv toolを使えます。
難点は開発終了したということです。

**Comment by warkene2** [comment]
この問題は正直非常に難しいですよね…最早署名うんぬんの問題ではなくWebExtension方式ではない旧式のコードで書かれたレガシーアドオン自体が弾かれるという事で、つまり現行のFirefoxに対応した新しいAnk Pixivをゼロから作らなければならない。しかし元々の作者さんは既にpixivを覗いておられないそうなのでそれをする可能性は限りなく低く、かといって別の作者さんが作るかといったらそれも分からないですし…

**Comment by ginzu** [comment]
overay extension版は、ginzuは今後メンテしないつもりです。
webextension版は、ほぼ完成しましたが署名を付けて配布することはないんじゃないかな～と思います。

このissueに関しては、以上です。

**Comment by ginzu** [comment]
webextension版もほぼ完成したのでこのissueはcloseとさせていただきます。
webextension版に対する改善要望がありましたら別途issueを立てて頂くようお願いします。

なお「webextension版をfirefoxで常用するにはどうするの！？」という点に関しましては、
[こちら](https://github.com/anekos/Ank-Pixiv-Tool/issues/137#issuecomment-334998669)にも書かせていただきましたが私もよくわかっていないのでご了承ください…m(_ _)m
