### ISSUE TITLE
火狐57版本，旧的附加组件将不能使用

### ISSUE THREAD

**Issue by xiaoxianxuan** [anekos/Ank-Pixiv-Tool#134]
请问新的附件组件何时开发完成？是否兼容以前的历史纪录？

**Comment by ginzu** [comment]
webextension版を試してみてください。 [webextension version](https://github.com/anekos/Ank-Pixiv-Tool/tree/feature/webextensions/webextensions/source)

履歴は旧版からJSONファイルにexportして、webextension版の設定からimportすることができます。 [script for dump](https://github.com/anekos/Ank-Pixiv-Tool/blob/feature/webextensions/webextensions/misc/dump_ankpixiv_sqlite.py)

**Comment by rehdv** [comment]
JSONへのエクスポートを行おうとしたのですが下記のエラーが発生してしまいました。
解決方法などわかりますでしょうか？

  File "dump_ankpixiv_sqlite.py", line 37
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by ginzu** [comment]
python2で書いてpython3で試してないのでそこかもしれません。
ちょっと2と3の差をググってみたところ、

> except Exception, e:

を

> except Exception as e:

と書き直すと動くみたいです（未確認）

**Comment by rehdv** [comment]
ありがとうございます。

>Exception as e:
>print (e)

にすることでPython3でもエラーの回避ができました。

しかし今度は下記のエラーが発生するようになってしまいました。
フォルダのアクセス権などは確認してありますが、他に考えられる原因はありますでしょうか。
Python等は未経験なので初歩的な間違いがあるかもしれませんがよろしくお願いします

C:\ankpixiv>python dump_ankpixiv_sqlite.py -i 'C:\ankpixiv\ankpixiv.sqlite' -o ankpixiv.json
unable to open database file
Traceback (most recent call last):
  File "dump_ankpixiv_sqlite.py", line 25, in main
    conn = sqlite3.connect(opts.src, isolation_level='DEFERRED')
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dump_ankpixiv_sqlite.py", line 39, in main
    if conn:
UnboundLocalError: local variable 'conn' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dump_ankpixiv_sqlite.py", line 50, in <module>
    main()
  File "dump_ankpixiv_sqlite.py", line 42, in main
    if conn:
UnboundLocalError: local variable 'conn' referenced before assignment

**Comment by ginzu** [comment]
dump script を python3用にコンバートしました。動作は確認済みです。
04a0b0f8178cedde2ebae992980aade75d895683

unable to open database fileというのはこちらでは発生しませんでした。

**Comment by rehdv** [comment]
対応ありがとうございます。
エラーはパスの受け渡しが上手く行っていなかったのが原因だったようでコード内に直接記述したところ無事エクスポートできました。

重ねての質問になってしまうのですが、
OSの入れ替え時等に履歴を引き継ぎたい場合はどのファイルをコピーすれば良いのでしょうか。

**Comment by ginzu** [comment]
設定画面のエクスポートが実装されるまでお待ちください。

**Comment by ginzu** [comment]
ダウンロード履歴のエクスポート機能、削除機能を実装しました。
https://github.com/anekos/Ank-Pixiv-Tool/commit/3071f4031f962a6fbadecbbc76f87371e406bacb

**Comment by ginzu** [comment]
ここでこのissueはcloseさせて頂きます。
以降のwebextension版に関する質問・要望は新規にissueを立ててくださいm(_ _)m
