### ISSUE TITLE
ニジエで漫画形式の投稿をDLする際の不具合

### ISSUE THREAD

**Issue by hinagesi** [anekos/Ank-Pixiv-Tool#135]
ニジエで画像複数枚の投稿をダウンロードしようとすると、
1枚目の画像を除いた残りの画像がサムネイルサイズでダウンロードされてしまいます。

**Comment by ginzu** [comment]
こちらもwebextension版で対応しました
https://github.com/anekos/Ank-Pixiv-Tool/commit/0e97cd878f9a7e1bd5a54e83b8d96950b58fc0e5

**Comment by ginzu** [comment]
特に問題なさそうなのでcloseします。
