### ISSUE TITLE
Twitterにおいてステッカー付きの画像を保存したい

### ISSUE THREAD

**Issue by hinagesi** [anekos/Ank-Pixiv-Tool#136]
要望になります。
投稿者がステッカーをつけて画像をアップロードしていると、その画像は本ツールでは保存できなくなっています。
これを通常の画像どおりワンクリックで保存できるようにして頂けないでしょうか。例えば以下のような画像です。
https://twitter.com/NozomiRuuuu/status/900641309274234880

**Comment by ginzu** [comment]
webextension版にて対応しました
https://github.com/anekos/Ank-Pixiv-Tool/commit/0e97cd878f9a7e1bd5a54e83b8d96950b58fc0e5

**Comment by Jahebi** [comment]
47.0.2, Sticker download does not work with latest feature/webextensions branch.
![2017-10-02_14-39-17](https://user-images.githubusercontent.com/6925916/31100741-843b7b32-a77f-11e7-8914-f5b4695f9a03.png)

**Comment by ginzu** [comment]
webextension版はFx47.0.2では正常に動作しないと思います。
webextension versrion does not work correctly on Fx47.0.2
