### ISSUE TITLE
タグ検索画面、背景が既読表示（ピンク）にならない。

### ISSUE THREAD

**Issue by bokodeko** [anekos/Ank-Pixiv-Tool#137]
お世話になります。

「タグ検索」画面において、こちらでも仕様・表示が変更されており、「保存済み」を示す「ピンクの背景」が表示されなくなってかなり経過しています（以前は横5でしたが、今は横4になっています。ちなみに作品画面では「保存済み／使用済み」の赤文字は出ています）。

対応、よろしくお願いいたします。

**Comment by ginzu** [comment]
『「タグ検索」画面』がどれかちょっとわからなかったのですが、作品のタグをクリックして表示されるページのことでしたらマーキングされるようにしました（webextension版）。

https://github.com/anekos/Ank-Pixiv-Tool/commit/9191ad8bd142bd6ef6043085b2cac29747eea4ae

**Comment by bokodeko** [comment]
ありがとうございます。（現在、Ank-Pixiv-Toolを使用するためにfirefoxを「ver42.0」に下げている状況）

説明不足で申し訳ありません。pixivにログインし、画面右上付近にある「検索ボックス」に「任意の単語等（例、ネコ）」を入力し表示される画面での事です。

あと、「Clone or download」からzipをダウンロード（PC保存）して解凍し、その中の「webextensionsフォルダ内にあるすべてをそのフォルダ構造のままzip圧縮する→拡張子xpiにする→firefoxにドロップ」の手順でいいのでしょうか？

よろしくお願いいたします。

**Comment by ginzu** [comment]
その画面でしたら上述のcommitで対応しています。

firefoxでwebextension版を常用する方法ですが、残念ながら私もよくわかっていません。
開発は主にchromeで行い、firefoxでは無署名extensionの一時的な読み込みを行えるテストツールを使って簡単な動作確認をしてるだけのためです。

・firefox extension ノーブラント版
・firefox extension 派生ブラウザ
・firefox extension 非公開 署名

こんな感じのキーワードで検索するとなにかそれっぽいのが出てくるので調べてみてください…m(_ _)m
