### ISSUE TITLE
Pixivの検索画面で、保存済みイラストかどうかが分らない（背景色が変わらない）

### ISSUE THREAD

**Issue by usr7072** [anekos/Ank-Pixiv-Tool#142]
いつもお世話になっております。
現段階で最新コミットのものをを使用していますが、検索画面で保存済み画像の強調表示がされていない状況になります。
Pixiv側のくデザインが変更されたことが主な原因かと思います。
優先度は最低で問題ありませんので、よろしければお手すきの際にご対応お願い致します。

**Comment by ginzu** [comment]
対応しました https://github.com/anekos/Ank-Pixiv-Tool/commit/eda805cddec91b4ca85fd461d80447e26730236e

原因はfirefoxでページ移動した際、document.readyState==='complete'になる以前にfocusイベントが発生していたため(chromeではそうでもない)。

**Comment by bokodeko** [comment]
失礼します。
先日同様の質問をさせていただいた者ですが、これで（私が使用しているものにも）適用された…のでしょうか？

よろしくお願いいたします。

**Comment by usr7072** [comment]
今はWeb　extentionsの方を中心に更新されているんですね・・・。これを機にそちらへ移行しました。
そして正常に動作することも確認しました。早い対応ありがとうございます。
DL履歴は書式合わせれば、SQLITE→JSONへ変換出来そうなので、うまい事やってみることにしました。

>>bokodekoさん
開発者の方でなくて申し訳ありませんが横から失礼します。

https://github.com/anekos/Ank-Pixiv-Tool/tree/master/source
こちらのURLで提供されているもの（ブランチ：master）は更新されていませんね。
ブランチ：feature/webextensions　のものが更新されているようなので、
可能であればそちらを使用すると良いかもしれません。
（Firefox 56.0.2でank pixiv3.0として動いています。普通にアドオンのアップデートから導入しました。しかし、以前のものと保存済みリストの互換性は無いようですので・・・）

認識違いがありましたらすみません。。

**Comment by ginzu** [comment]
特に問題ないようですのでcloseします。

**Comment by usr7072** [comment]
ご対応いただき、ありがとうございました。
