### ISSUE TITLE
Firefox56でのwebextentionの使用について

### ISSUE THREAD

**Issue by yuji123** [anekos/Ank-Pixiv-Tool#143]
お忙しい中、失礼します

使用環境：Firefox  Developer Edition 56.0b12 (64 ビット)

firefoxdev56でのwebextentionの使用について
Ank-Pixiv-Tool-e613e0054fa93543d7678238d73b43eb0b94e203
のバージョンをパッケージとしてインストールした場合、アドオンの設定画面が、チェックボックスやインポートエクスポートボタンのみ表示され、文字が一切表示されない状態になってしまい、使用することができません。
この場合はどうすればよいか、アドバイスをお願いします。

また、エクスポートボタンも使用できないので旧式である「Ank-Pixiv-Tool　2.1.3」の履歴を現在のwebextention版で使用するにはどうすればよいですか？
質問ばかりで申し訳ありませんが、回答をお願いします

**Comment by enoki5150** [comment]
ank pixiv tool 3.0ありがとうございます！
データベースになるankpixiv.jsonはどこに格納されているんでしょうか？
プロファイルフォルダに見当たらないんですが

**Comment by k2krobo** [comment]
旧Ank-Pixiv-Toolの履歴をwebextention版へインポートする件については、以下のリンクが参考になるかと思います。
https://github.com/anekos/Ank-Pixiv-Tool/issues/134

**Comment by ginzu** [comment]
再現性が不明です。
