### ISSUE TITLE
Choosing a different download folder

### ISSUE THREAD

**Issue by mignonette** [anekos/Ank-Pixiv-Tool#144]
In "preferences", the images can only be downloaded to the computer's default downloads folder. Will and when there be an option to choose which user-made folder the images are downloaded to? Eg. "Pictures" or "Pixiv"

**Comment by Philmist** [comment]
Please use "Symbolic Link".
Firefox's WebExtension cannot save files outside of default downloads folder.

**Comment by ginzu** [comment]
Philmist さんの仰る通り webextension api の仕様に起因する制限ですm(_ _)m
