### ISSUE TITLE
webextention版　pixivでの複数画像の作品のダウンロードについて

### ISSUE THREAD

**Issue by k2krobo** [anekos/Ank-Pixiv-Tool#148]
お世話になっております。
現在、Firefox 56.0.2 で、webextention版を使用しています。

pixiv で複数画像の作品をダウンロードしようとすると「情報取得中」の表示のまま進みません。
(1枚の画像しかないものはダウンロード可能でした)
確か数日前に複数画像の作品をダウンロードしたときは正常にダウンロードすることができました。

お手数ですが、ご確認いただけますでしょうか。

**Comment by k2krobo** [comment]
自己解決しました。
設定 > ビュアー > 「オリジナルサイズの画像を表示する」
のチェックを外していると上記の現象が発生しました。

お騒がせしてすみませんでした。
こちら、クローズしておきます。

**Comment by ginzu** [comment]
修正しました。情報ありがとうございます。

**Comment by k2krobo** [comment]
修正ありがとうございます。
