### ISSUE TITLE
旧版の保存履歴の引き継ぎ方

### ISSUE THREAD

**Issue by kanarimegane** [anekos/Ank-Pixiv-Tool#150]
3.0.0版の更新ありがとうございました。早速更新させて使わせて頂いてます
旧版の保存履歴が新しいバージョンでは使えなくなっていたのでこちらの書き込みを元に引き継ごうとしたのですがプログラミングとgithubの知識があまりなくうまく行きませんでした
https://github.com/anekos/Ank-Pixiv-Tool/issues/143

引き継ぎ方についてどなたか詳しく教えてくださる方いますか？

**Comment by ckypk2003** [comment]
Same question.
I have already downloaded dump_ankpixiv_sqlite.py and installed python3 but how to use it?
Thanks.

**Comment by riQwn** [comment]
1. Download and install python3
2. Download [dump_ankpixiv_sqlite.py](https://github.com/anekos/Ank-Pixiv-Tool/blob/master/webextensions/misc/dump_ankpixiv_sqlite.py).
3. Locate ankpixiv.sqlite in your browser profile folder, e.g. inside `C:\Users\<YourUserName>\AppData\Roaming\Mozilla\Firefox\Profiles\<ProfileName>.default\` for Windows/Firefox and copy ankpixiv.sqlite to a folder of your choice. This is your original download history.
4. Run dump_ankpixiv_sqlite.py with the input option -i SRC and output option -o DST, e.g. on Windows you can use Command Prompt with the command `<full path of python.exe> <full path of dump_ankpixiv_sqlite.py> -i <full path of ankpixiv.sqlite> -o <full path of output.json>`.
It should look similar to this: 
```
C:\Users\<YourUserName>\Appdata\Local\Programs\Python\Python36-32\python.exe C:\Users\<YourUserName>\Desktop\dump_ankpixiv_sql
ite.py -i C:\Users\<YourUserName>\Desktop\ankpixiv.sqlite -o C:\Users\<YourUserName>\Desktop\ank
pixiv.json
```
5. Run the script and it should convert your sqlite download history to a json file.
Only thing left to do is to open the AnkPixiv options in your browser and use the "Import download history" option to import the json file.

**Comment by ckypk2003** [comment]
It works. Thanks for your detailed answer.

**Comment by kanarimegane** [comment]
解決しました
非常に丁寧な解説ありがとうございました
Thank you!!
