### ISSUE TITLE
Firefox 57.0b14 (64 bit) twitterの画像のダウンロードが失敗する

### ISSUE THREAD

**Issue by unthinking** [anekos/Ank-Pixiv-Tool#151]
ank pixiv tool 3.0.0 (2017/10/26)を利用しています。
ボタンを押してtwitterの画像を保存しようとすると”ダウンロード失敗！”と表示されるのですが自分の環境だけでしょうか。
失敗するのはFirefox 57.0b14 (64 bit) においてのみです。
Chrome 62.0.3202.75（Official Build）（64 bit）では保存できます。
OSはWindows7 home premiumです。

**Comment by potato-starch** [comment]
原因が同じかどうかわかりませんが、ank pixiv tool 3.0.0 (2017/10/26)で、Firefox 56では動作し、Firefox57(64 bit)にアップデートしたところ同様の症状が発生しました。
Firefoxのオプションのトラッキング保護を解除することで動作するようになりました。

**Comment by unthinking** [comment]
トラッキング保護を解除、試してみたところfirefox58.0b4(64bit)でtwitter画像をダウンロードできるようになりました。
57以降の問題のようですね。
