### ISSUE TITLE
Artist Gallery download?

### ISSUE THREAD

**Issue by JarieSuicune** [anekos/Ank-Pixiv-Tool#153]
Add Artist Gallery download option?

**Comment by ginzu** [comment]
通常閲覧時以上の負荷をサーバにかけないというポリシーで開発しているので、一括ダウンロード・オートパイロット・サムネから直接DLといった機能は実装しません。

**Comment by QuessParaya** [comment]
From what I understand, after running ginzu's statement in Google Translate, he says that in consideration for the Pixiv server, he does not implement automatic downloads of whole galleries.
