### ISSUE TITLE
What happened to the ability to include page numbers in the filename

### ISSUE THREAD

**Issue by LawRon** [anekos/Ank-Pixiv-Tool#155]
I'm not particularly fond of saving artist galleries to individual folders, especially when in most cases the gallery only consists of 2-3 images.
What happened to the option of saving images with the page number in the filename like so:
"Example page00 by whoever"

**Comment by ginzu** [comment]
"#page-number#" tag は廃止されました。

代わりに "Store multiple images manga in one folder." option を新設しました。
enable の場合 who/image/1.jpg, who/image/2.jpg, ... の様に保存します。
disable の場合 who/image -1.jpg, who/image - 2.jpg, ... の様に保存します。
現状、書式は 「"filename" - "pageno"."ext"」固定となっています。
