### ISSUE TITLE
[要望]保存先を毎回指定する設定を復活させて欲しい

### ISSUE THREAD

**Issue by Mphilia** [anekos/Ank-Pixiv-Tool#156]
いつも使わせていただいております。
2.1.2ではその設定があったのですが、3.0.0になってから全てのファイルが1クリックで「ダウンロード」フォルダに保存させられるようになりました。
気づくと「ダウンロード」フォルダに画像が1000枚くらい溜まっていて、ファイルの仕分けするのに膨大な時間が掛かってしまい、出来ればDLする時点で仕分けも同時に済ませたいです。
どうか保存先を毎回指定する設定を復活させて欲しいです。
ご検討のほどよろしくお願いします。

**Comment by bokodeko** [comment]
以前のバージョンは保存時毎に「フォルダ選択」ができましたが、指定できなくなり一つのフォルダに保存されるようになりました。（すでにスレ主が述べられている通り）また、「AnkPixiv」というフォルダも自動に作られておりまして、なんとか以前の仕様のように保存先フォルダ選択ができるようにしていただけませんでしょうか？（本日、pixivの仕様変更で「フォロー新着絵」が横四列になり、firefoxを最新のものに更新し、自動的に同ツールも3.0.0になった次第です）

**Comment by ginzu** [comment]
こちらをご一読ください。
https://github.com/anekos/Ank-Pixiv-Tool#user-content-changes-from-2xx
