### ISSUE TITLE
Firefox ESR 52.5.2でダウンロードできない

### ISSUE THREAD

**Issue by enoki5150** [anekos/Ank-Pixiv-Tool#157]
- 発生した問題の詳細/Firefox ESR 52.5.2にインストールしたらダウンロードできない
- 発生したURL/pixiv全般
- 再現手順/Firefox ESR 52.5.2にインストールしたらダウンロードできない。portable56.0.1では問題なくできる。
- Ank Pixiv Toolのバージョン/3.0
- ブラウザのバージョン/Firefox ESR 52.5.2

**Comment by ginzu** [comment]
52くらいの古いfirefoxだとank pixiv toolで使用するwebextension APIの実装が不足しているので動作しないと思います。

**Comment by enoki5150** [comment]
そうなんですか。じゃあ他のものに切り替えてみようと思います。
あとなぜか他のダウンロードが完了するの同時にダウンロードアイコンをクリックするとダウンロードできます
