### ISSUE TITLE
[要望] ニコニコ静画 (マンガ) への対応

### ISSUE THREAD

**Issue by kahusi** [anekos/Ank-Pixiv-Tool#158]
旧版で対応してた「ニコニコ静画 (マンガ)  http://seiga.nicovideo.jp/manga/」にも対応していただければ有り難いです。

**Comment by ginzu** [comment]
結構前に難読化とおぼしき変更が入りました。これは運営からの「ダウンロードしてくれるな」というメッセージと判断しました。なので、対応することはありません。

**Comment by kahusi** [comment]
成程了解しました。
