### ISSUE TITLE
「画像を見つけられませんでした」と出る

### ISSUE THREAD

**Issue by bokodeko** [anekos/Ank-Pixiv-Tool#159]
先程pixivに入り、画像を保存しようとしましたら以下（タイトル）のエラーが出て画像保存ができない状態です。ツイッターの方は問題なく保存できました。（2月19日17:00現在）

- 発生した問題の詳細/「画像を見つけられませんでした」と出る。（赤文字で「情報取得中」のまま移行せず）
- Ank Pixiv Toolのバージョン/3.0.0
- ブラウザのバージョン/firefox58.02

昨日から特に設定等々いじっていませんが、固有の事象なのでしょうか？よろしくお願いいたします。

**Comment by ginzu** [comment]
変更に対応した修正クエリを作成しました。

オプション画面　＞　セレクタ上書き設定のインポート／消去　＞　インポートボタン

から取り込んでください（ファイルセレクタは*.jsonでフィルタしているので、ファイル名の.txtは削除する等の対応を願いします）。

[override_selector_20180219.json.txt](https://github.com/anekos/Ank-Pixiv-Tool/files/1736628/override_selector_20180219.json.txt)

なおこのissueについては、closeはこちらでおこないますので問題が解消してもopenしたままでお願いします（同じ問題で訪問する方が多いと思うので、見つけやすくするためです）。

**Comment by enoki5150** [comment]
ありがとうございました
新しいFirefoxの仕様上アドオン自体がバージョンアップするまで無理かと思ってました

**Comment by QuessParaya** [comment]
Thank you, Mr. Ginzu.

**Comment by bokodeko** [comment]
お返事遅れましたが、早速の対応恐縮です。
DLしたものそのままインポートし（何かと便利な仕様になったんだなと、早速（当日中）解消済みです。ありがとうございました。

スレ閉じの件、ginzu殿にお任せいたします。

**Comment by ginzu** [comment]
修正版の3.0.1をAMOにアップロードしました。
