### ISSUE TITLE
作者名・タイトルの先頭に"."が含まれているとダウンロードに失敗する

### ISSUE THREAD

**Issue by potato-starch** [anekos/Ank-Pixiv-Tool#160]
- 発生した問題の詳細/Trouble details
ダウンロード開始してすぐに「ダウンロード失敗！」が表示されます。
作者名、もしくはタイトルの先頭に"."が含まれていることが条件のようです
少なくともPixivとTwitterで確認、他のサービスは不明
- 発生したURL/URL
作者名の例
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=66280998
https://twitter.com/sukemyon_443
タイトルの例
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=67392381
- Ank Pixiv Toolのバージョン/Ank Pixiv Tool Version
3.0.0
https://github.com/anekos/Ank-Pixiv-Tool/files/1736628/override_selector_20180219.json.txt 適用済み
- ブラウザのバージョン/Browser Version
Firefox 58.0.2(64 bit)

**Comment by ginzu** [comment]
現象を再現できませんでした。

設定している保存時ファイル名のフォーマットと、失敗時にコンソールに出力されるログ（ログレベルをDEBUG以上にして）を頂けますか？

**Comment by potato-starch** [comment]
すみません、ログの取り方を教えていただけないでしょうか？

設定していた保存時ファイル名のフォーマットは
AnkPixiv/?site-name?/?memoized-name? (?member-id?)/?title? (?illust-id?)
でしたが、デフォルトの
AnkPixiv/?site-name?/(?member-id?) ?memoized-name?/?illust-year?-?illust-month?-?illust-day? (?illust-id?) ?title?
に戻したところ正常にダウンロードできました。

**Comment by ginzu** [comment]
ファイル名 or フォルダ名の先頭に "." があるとdownloads apiがエラーを返すことが分かりました。
Firefox/Chrome、Windows/Ubuntuのいずれでも同様なので仕様のようです（明記してあるドキュメントは見つけられませんでした）。
次の修正の際にファイルセパレータ直後の"."を他の文字にする（"hoge/.piyo.jpg" → "hoge/_piyo.jpg"）回避策を入れたいと思いますが、しばらくは設定での回避をお願いします。

ログについては、[ブラウザコンソール](https://developer.mozilla.org/ja/docs/Tools/Browser_Console)を開いてそこからコピペでOKです。

**Comment by ginzu** [comment]
修正版の3.0.1をAMOにアップロードしましたので更新ののちご確認ください。
問題なければcloseお願いします。

ログについてはそんな感じでOKです。
