### ISSUE TITLE
Illustration tags in the metadata saved from the Nijie site are confusing.

### ISSUE THREAD

**Issue by sorkgh** [anekos/Ank-Pixiv-Tool#161]
- 発生した問題の詳細/Trouble details
Some illustration tags in the metadata saved from the Nijie site are (mistakenly?) including the asterisk. E.g. a tag which is named "かわいい" may be recorded as "*かわいい". Since the asterisk is a special mark on the site's tag system, but has nothing to do with the tag itself, I think this might be a bug. Also, the tags recorded from the Pixiv site don't have this problem.
This makes me confused while trying to deal with these tags, since it is hard to figure out whether the asterisk is a part of the tag or just a special mark for the tag.

- Ank Pixiv Toolのバージョン/Ank Pixiv Tool Version
3.0.0 & 3.0.1 (webextensions version)

- ブラウザのバージョン/Browser Version
Firefox 56.0.2 (x64)

**Comment by ginzu** [comment]
Sorry, it is my mistake.
すみません、2.xから3.xにコンバートする際にコードを書き損じてしまいました。
I will fix it in 3.0.2.
3.0.2で直します。

**Comment by ginzu** [comment]
I released 3.0.2 on AMO. Please try it.
AMOに上げたので試してみてください。

**Comment by sorkgh** [comment]
Wow! Thanks for your super fast replying and bug fixing. I have tried the new version on some illustrations and it works pretty well now.

Yet I have another question. The illustration captions saved from the Pixiv did not record the line breaks, while the old 2.x versions did record them. Is this a design change or a bug? Either, I thought it would be better if the line breaks in the captions can be correctly recorded. Thanks again!

**Comment by ginzu** [comment]
> Is this a design change or a bug?

It's my mistake, too.
同じくデグレードです。
I fixed it in 3.0.3 and released.
修正してAMOに上げたので確認よろしくお願いします。

**Comment by sorkgh** [comment]
I've tried the new version and it is able to save the line breaks now. Thank you very much!
