### ISSUE TITLE
Changing color of "already downloaded" images

### ISSUE THREAD

**Issue by tttttrrrrreeeee** [anekos/Ank-Pixiv-Tool#163]
- 発生した問題の詳細/Trouble details
This is not actually an issue with the tool, there is no trouble. But some "already downloaded" images on Pixiv are marked with pink background, others turquoise. It seems the color choice is related to whether file is jpg/png/ugoira but that's not the only factor. I want to mark all downloaded files on Pixiv with, for example, paleturqoise color. Can I do this?
I am using Chrome 64.0, AnkPixiv 3.0.2
Sorry for posting an issue when it is not actually an issue. Thank you

**Comment by ginzu** [comment]
(1)
background color means
背景色には以下の意味があります

lime: while downloading
pink: downloaded
turquoise: downloaded, but it has been updated by creator (unfortunately, sometimes caption changes only)
緑色: ダウンロード中
赤色: ダウンロード済み
水色: ダウンロード後に更新されている (画像ではなく、キャプション変更のみの場合もあります)

(2)
background color style is defined in "css/style.css"
cssをいじることで背景色を変更することは可能です。 css/style.css を参照してください

(3)
I forgot to write "ignore detect update" option. I will add it later
"更新の有無を確認する"オプションを入れ忘れていました。そのうち書き足します
