### ISSUE TITLE
ニジエで複数ページ作品がDLできない？

### ISSUE THREAD

**Issue by bokodeko** [anekos/Ank-Pixiv-Tool#166]
- 発生した問題の詳細/ニジエで複数ページ作品（二頁目以降）
-Ank Pixiv Toolのバージョン/3.0.4
- ブラウザのバージョン/Firefox59.0.2

先程試してみたのですが、ニジエにおいて複数ページ作品の二頁目以降がダウンロードできないみたいです。

設定等はここしばらく触った記憶がないのですが、設定上の問題なのでしょうか？

よろしくお願いいたします。

**Comment by ginzu** [comment]
Sorry, "Selector Override" doesn't function well on 3.0.4.
3.0.4で「セレクタ上書き設定」が機能していません。すいません。

**Comment by ginzu** [comment]
I released 3.0.5. Please try it.
修正してAMOに上げたので確認よろしくお願いします。
