### ISSUE TITLE
pixivの画像が保存できなくなりました

### ISSUE THREAD

**Issue by enoki5150** [anekos/Ank-Pixiv-Tool#169]
- 発生した問題の詳細 pixivの画像が保存できなくなりました。多分また仕様変更だとおもいますが。
あとなぜかダウンロード履歴のエクスポート／インポートができなくなっています(インポートのほうは起動して最初の一回だけはできます)
- 発生したURL/https://www.pixiv.net/
　　　　　　　(pixiv全体)
- 再現手順/画像を保存しようとアイコンをクリックしても反応しない
- Ank Pixiv Toolのバージョン/Ank Pixiv Tool Version
- ブラウザのバージョン/59.0.3＆56.0.2(portable)
- 特記事項　他のアドオンを全て停止しても同じです。あとCSSを使って多段タブを実現してます。

あと質問ですがpixivFANBOXやファンテイアなどの絵師支援サイトの画像に対応する予定はありますか？
それとankpixiv.jsonはプロファイルフォルダのどこにあるんでしょうか？

**Comment by ginzu** [comment]
前者は #167 、後者は #164 で対応します。

**Comment by ginzu** [comment]
pixivFANBOXへの対応予定はありません。

XUL版とは異なり履歴情報の保存はブラウザの実装に依存しているため直接アクセスは推奨しませんし、こちらから情報を出すこともありません。
