### ISSUE TITLE
ダウンロード履歴のエクスポートが正常に機能しません

### ISSUE THREAD

**Issue by yoshiyoshiX** [anekos/Ank-Pixiv-Tool#172]
- 発生した問題の詳細/Trouble details

ダウンロード履歴のエクスポートが正常に機能しません。
エクスポートボタンを押したとき、
histories exported XXX
という文字が右側に表われた後、数値が上昇していき、histories exported 131000 のように履歴は全て読み込まれてたようです。
次に、members exported XXX と completed のような文字が表示されました（速すぎてよく確認できなかったので不正確かもしれません）。
その後、真っ白で何も表示されない画面に切り替わり、Ank Pixiv Tool のタブを見るとずっと読み込み中の表示になったまま、一向に処理が終わる気配がありません。
お手数おかけしますが、解決方法を教えて頂けますか。

- 発生したURL/URL
Ank Pixiv Tool 設定画面

- 再現手順/Steps to reproduce
エクスポートボタンの実行

- Ank Pixiv Toolのバージョン/Ank Pixiv Tool Version
3.0.5

- ブラウザのバージョン/Browser Version
Firefox 56.0.2

- 特記事項(設定や使用中のアドオンなど)/Special notes(configurations, add-on list, etc.)
大量（13万以上）のダウンロード履歴があります。

**Comment by ginzu** [comment]
Windows7(64bit)の仮想環境に56.0.2(32bit版)をインストールして40万件強の履歴をインポート→エクスポートしてみましたが、正常に完了しました。
環境に依存する問題ではないかと思われます。

**Comment by yoshiyoshiX** [comment]
Firefox 60.0.1 に上げて試してみましたが、エクスポートボタンが無反応になりました。

**Comment by ginzu** [comment]
直接関係あるかはわかりませんが、option_pages.htmlのエクスポートボタンのonclickアトリビュートに対して「extension中のhtmlにインラインスクリプト書くなよ」警告が出ていたので修正しました。

clickイベントを無効化できていないとボタン押下後にどこでもないページに遷移しようとして真っ白になる…ということはあるような気がするので、もしかしたらこれで直っているかもしれません。

直ってなかったらすみません。

**Comment by yoshiyoshiX** [comment]
ご対応ありがとうございます。
残念ながら症状は変わらずでしたが、Firefoxを再インストールしてみたら直りました。
本当にありがとうございました。
