### ISSUE TITLE
pixivの仕様変更

### ISSUE THREAD

**Issue by kahusi** [anekos/Ank-Pixiv-Tool#173]
member_illust.php が仕様変更し、動作しなくなったので一往立てておきます。

うちの環境: Win7Pro64bit+Firefox60.0.1

**Comment by ginzu** [comment]
#167 とは別件ですか？

**Comment by kahusi** [comment]
例えば https://www.pixiv.net/member_illust.php?mode=medium&illust_id=20 等何でも良いのですが、
数日前とサイトのデザインが全然違っているのです。

**Comment by ginzu** [comment]
やはり同じ件と思われるので、あちらに合流してこちらはcloseしてください。

あちらで公開している最新commitで動作するなら、既に対応済みの仕様変更です。
動かないのであれば、その仕様変更は私のアカウントにはまだ適用されていなためコードを書くことができません。

**Comment by kahusi** [comment]
#167 でのwebextで動作しました。お手数お掛けしました。

# ユーザによってデザイン変更のタイミングが違うと読取りましたが合ってるのかな。
