### ISSUE TITLE
Pixiv has changed (2018.04) / Pixivの新デザインへの対応 (2018.04)

### ISSUE THREAD

**Issue by ginzu** [anekos/Ank-Pixiv-Tool#174]
★ Please read #167 first.
★ 先に #167 を読んでください

---

Pixivの仕様変更は今後もしばらく続くと思うので、この件に関してはこのissueを使ってください。

ところで新デザインでは各class名が自動生成のランダムな値になっています。
そのためちょっとしたメンテでも全然別な値に変わってしまい動作しなくなる時があります。
47371cb はその例です。

なので「動きません」レポートには具体的に「ここがこう変わったっぽいよ？」まで踏み込んで書いて頂けるとみんなハッピーになれるかもしれません。

**Comment by bokodeko** [comment]
いつもお世話になります。

この場にて失礼します。現在の同ツールは新デザインに対応したものですが、（仮定の話として）pixiv側の事情で前デザインに戻った場合、対応の同ツール(3.0.5)はどこから入手すればよいのでしょうか？

よろしくお願いいたします。

**Comment by UME158** [comment]
私も動かなくなり、アドオンを全て削除した所、アドオンがインストールできない等、
他の問題が発生しております。
60.0.2へUpDateした所発生しております。
一気に上げたのが原因かもしれませんが・・・

**Comment by ckypk2003** [comment]
The below link cannot be saved, would you please help to check. Thanks. 
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=69216079

**Comment by noname001a** [comment]
pixiv新デザインでなぜかダウンロードできました

Ank Pixiv Tool 3.0.6
Firefox 56.0

**Comment by usr7072** [comment]
@UME158 
開発者ではないですが、その問題はお使いのFirefox本体かプロファイルの問題のように見えます。

質問1：アップデートしたとのことですが、Firefoxの自動更新機能でのアップデートでしょうか？
　　　☞自動更新のアップデートでしたら、Firefoxのフルパッケージをインストールして試してみてください。
質問2：「Firefoxのリフレッシュ」を試しているでしょうか？
　　　☞試していないのであれば、画面右上の　三　をクリックし、「トラブルシューティング情報」、「Firefoxのリフレッシュ」より設定の初期化を試してみてください。
　　　☞初期化するのが嫌でしたら、新たテスト用として、Firefoxプロファイルの追加をして試してください。

初期化する場合は、Firefoxプロファイルが保存されている
C:\Users\**ユーザー名**\AppData\Roaming\Mozilla フォルダをデスクトップなどに丸ごとコピーし、
元の状態に戻す場合は「C:\Users\**ユーザー名**\AppData\Roaming\Mozilla 」を丸ごと削除するか、
フォルダ名を変更したのちに、デスクトップにコピーしたmozillaフォルダを「C:\Users\**ユーザー名**\AppData\Roaming\」内にコピーすればすべて楽に戻ります。

プロファイル追加は検索すればいくらでも出てきますので、ご自分でお探しください。

**Comment by ginzu** [comment]
@eulpnu 
再現できませんでした。
?memoized-name?単独の問題ではないかもしれないので、保存時ファイル名の設定をフルで教えて頂けますか？

またこれはPixivの新デザインの件とは別件かな？と思うので、別のissueを立ててそちらでやりましょう。

**Comment by eulpnu** [comment]
お返事ありがとうございます。issue立てましたのでお手すきの際にご確認いただければありがたいです。

**Comment by kknine99** [comment]
発生した問題の詳細/Trouble details
It seems that pixiv has change something,  the ?title? tag couldn't get the artwork's title correctly.

Ank Pixiv Toolのバージョン/Ank Pixiv Tool Version
3.08
ブラウザのバージョン/Browser Version
Firefox 61.0.1(64 bit)

**Comment by typetonk2** [comment]
またPixivの仕様変更でしょうか。
ひとまず一部セレクタを修正してみた所、DL出来るようになりました。

セレクタ上書き設定で使用したjsonファイルを置いておきます。
修正の参考になれば幸いです。

[override_selector_20180718.json.txt](https://github.com/anekos/Ank-Pixiv-Tool/files/2205829/override_selector_20180718.json.txt)

**Comment by bokodeko** [comment]
typetonk2さん、こんばんは。

上記データ、ありがとうございます。なんとかDLできていまして、助かりました。

（見た感じ仕様変更されたように気付きませんが…どうなっているのでしょうかね？）

**Comment by bokodeko** [comment]
何度も、失礼します。

@typetonk2さんに示していただいた「override_selector_20180718.json.txt」のあとにginzuさんから示された e2f2bef と 26a0f29 のDL方法はどうしたらいいのでしょうか？（どちらが7/18日発生案件への対応ファイルなのでしょうか？）

よろしくお願いいたします。

**Comment by annie0427** [comment]
@typetonk2 think you very much !!
@ginzu how to use e2f2bef ??

**Comment by typetonk2** [comment]
@ginzu 
修正ありがとうございます。
https://github.com/anekos/Ank-Pixiv-Tool/commit/e2f2bef8aa2a60a70614df3eb440374c60c0c701 を適用して、無事DL出来ました。

@bokodeko 
私の提示したファイルはあくまで一時的な回避策のため、
https://github.com/anekos/Ank-Pixiv-Tool/commit/e2f2bef8aa2a60a70614df3eb440374c60c0c701 を適用したほうがいいと思います。
[#167](https://github.com/anekos/Ank-Pixiv-Tool/issues/167#issuecomment-391324200)のコメントによると、過去のissueのどこかにやり方は書いてあるそうです。

**Comment by zel3** [comment]
誰かDLと適応の仕方を教えてください

**Comment by zel3** [comment]
直し方がわからないので誰か教えてください

**Comment by kknine99** [comment]
@ginzu Thank you. The e2f2bef works fine.

**Comment by pikomari** [comment]
必要な人がいるかわかりませんが自分の解決法を
e2f2bef をdlしてWebExtension内のSourceをパッケージング後、firefox公式より署名→DLすれば読み込めました

**Comment by noname001a** [comment]
sourceフォルダにmisc/get_pixiv_classname_aliases.jsをコピーすればいいの？

**Comment by bokodeko** [comment]
お世話になります。

    発生した問題の詳細/「画像を見つけられませんでした」となる
    Ank Pixiv Toolのバージョン/3.0.9
    ブラウザのバージョン/firefox61.0.1(32bit)

「画像を見つけられませんでした」との表示が出るようになりました。（昨日、本日の深夜までは普通に保存できてました）

お忙しいところ申し訳ありませんが、対処をよろしくお願いいたします。

**Comment by bokodeko** [comment]
お世話になります。

発生した問題の詳細/「画像を見つけられませんでした」となる
Ank Pixiv Toolのバージョン/3.0.9
ブラウザのバージョン/firefox61.0.1(32bit)

「画像を見つけられませんでした」との表示が出るようになりました。

お忙しいところ申し訳ありませんが、対処をよろしくお願いいたします。

**Comment by ginzu** [comment]
[override_selector_20180725.json.txt](https://github.com/anekos/Ank-Pixiv-Tool/files/2227801/override_selector_20180725.json.txt)

**Comment by enoki5150** [comment]
素早い対応ありがとうございます

**Comment by pekeko** [comment]
Ank Pixiv Toolのバージョン/3.0.9
ブラウザのバージョン/firefox61.0.1(64bit)

こちらでも動作正常になりました！
迅速なご対応ありがとうございます！

**Comment by SWN-002** [comment]
Hello
After the latest update of Ank Pixiv Tool, the download function worked.
However, it seems the "Cannot find image" problem happened again today.

Ank Pixiv Tool 3.0.9
Firefox 61.0.1(64 bit)

I've tried on Windows 10 and MacOS 10.12.6, both of them have the same problem.

**Comment by bokodeko** [comment]
お世話になります。
早速の対応、ありがとうございました。（おかげさまで、問題なく動作しております）

さて、先週に引き続いて今週も「(水曜日に)なにかしらの変更」があったのかもしれませんが、聞くところでは、31日から「プロフィール画面の仕様変更」も始めるとか…。

まだまだ安定しないpixivの仕様変更ですが、今後とも何卒よろしくお願い致します。

**Comment by pikomari** [comment]
すいませんoverride_selector_20180725.json.txtは何処と差し替えればいいのでしょうか？

**Comment by noname001a** [comment]
Ank Pixiv Tool＞設定＞「セレクタ上書き設定のインポート」から
override_selector_20180725.json.txtを読み込むと保存できるようになります

**Comment by bokodeko** [comment]
お世話になります。

本日、また「画像を見つけられませんでした」になっているようです。（15時40分現在）

**Comment by bokodeko** [comment]
お世話になります。

本日、また仕様を一部変更したのか「画像を見つけられませんでした」になっているようです。（16時現在）

**Comment by ginzu** [comment]
[override_selector_20180729.json.txt](https://github.com/anekos/Ank-Pixiv-Tool/files/2240995/override_selector_20180729.json.txt)

**Comment by ginzu** [comment]
[override_selector_20180730.json.txt](https://github.com/anekos/Ank-Pixiv-Tool/files/2241081/override_selector_20180730.json.txt)

**Comment by Drat57** [comment]
いつも対応ありがとうございます
Twitterの画像を保存しようとするとダウンロード中と出てそのままタイムアウトで
ダウンロード失敗となってしまうようです

Firefox61.01(64bit)
Ank Pixiv Tool 3.0.10

**Comment by Drat57** [comment]
失礼しました、別で立てさせて頂きました　#180

**Comment by Drat57** [comment]
失礼しました、別で立てさせて頂きました　#180

**Comment by Drat57** [comment]
失礼しました別で立てさせて頂きました　https://github.com/anekos/Ank-Pixiv-Tool/issues/180

**Comment by bokodeko** [comment]
お世話になります。

本日(16時現在)「画像を見つけられませんでした」になっています。（pixiv側は一体どこをどう弄ってるのでしょうね…）

いつもいつも申し訳ありませんが、よろしくお願い致します。

**Comment by kayamai** [comment]
`.work_info`というhtml classがなくなって、html構造も変化しているようです。
セレクタのdatetime, title, caption, tagsがnullになります。
```
    "datetime": {"s": "figcaption div[title=\"投稿日時\"]"},
    "title": {"s": "figcaption h1"},
    "caption": {"s": "figcaption p"},
    "tags": {"ALL": "figcaption footer > ul > li > span > a"}
```
この書き方であっているか不安ですが……
急ぎ報告まで。

**Comment by zel3** [comment]
どうすればDLできるようになりますか？

**Comment by winiah** [comment]
Ank はあくまでデータベースなので、普通に画像保存すれば、DLだけはできる。

今まで通り、Pixiv 側に変更があったら、更新を待つのみ。
もしくは自分で ankpixiv@snca.net.xpi をいじるとか。

もし Pixiv のこのような仕様変更が常態化になるとしたら、
Ank にデバッグ仕様を入れ、画像の新しい URL の探し方（セレクタ）、
それをユーザー側にも簡単に変更できたりすれば、
このスレにコピペ用のソースを用意するだけでアプデの必要もなくなるのでしょう。

ぶっちゃけ Pixiv の仕様変更の理屈がわかりづらいから、
いちいち対応するのは面倒い（といってもボクはデベロッパーさんではないけどね）

**Comment by SikigamiHNQ** [comment]
上にあるセレクタ設定の変更内容を、既存の上書きJSONの内容を参考にして自分でJSONファイルを
作成してインポートしたら、うまくＤＬできるようになりました。ありがとうございます。
JSONファイルの文字コードをUTF8にする必要があることに気がつくのにしばらくかかりましたがｗ

しかし、ここまでホイホイ変えられると、こういうＤＬツールの阻害のためにテキトーに変更してるんじゃないかって気がしてきますね。

**Comment by zel3** [comment]
何をどうするのか教えてもらえますか？

**Comment by zel3** [comment]
UTF8などもよくわからない初心者なのでわかりやすく教えてもらえると助かります

**Comment by enoki5150** [comment]
1. override_selector_20180730.json.txtをダウンロード
2. 拡張子.txtを削除してoverride_selector_20180730.jsonに拡張子を変える
3. テキストエディタにoverride_selector_20180730.jsonをドラッグ・アンド・ドロップして開く(僕はEmEditerというソフトを使いましたが多分どんなエディタでもできます)
4. 
"datetime": {"s": ".work-info .meta > li, figure+div > ul+div"},
を
"datetime": {"s": "figcaption div[title=\"投稿日時\"]"},
に
"title": {"s": ".work-info .title, figcaption > h1"},
を
"title": {"s": "figcaption h1"},
に
"caption": {"s": ".work-info .caption, figure figcaption > h1+div p"},
を
"caption": {"s": "figcaption p"},
に
"tags": {"ALL": ".work-tags .tags > .tag > .text, figcaption > footer > ul > li > span > a"}

を
"tags": {"ALL": "figcaption footer > ul > li > span > a"}
にそれぞれ置き換え

5. 失敗したときに備えて名前を変更して保存。この時に文字エンコードという項目があるのでUTF-8(BOM無し)で保存します。

6. 出来上がったjsonファイルをank pixiv toolの設定画面のセレクタ上書き設定のインポート／消去のインポートで読み込む

これで出来た

SikigamiHNQさんありがとうございました

**Comment by enoki5150** [comment]
override_selector_20180730.json.txtはこのスレの上の方にあります

**Comment by enoki5150** [comment]
最後にkayamaiさんありがとうございました

**Comment by bokodeko** [comment]
すいません、enoki5150さんの方法(EmEditerもDLしてみて)で保存した「override_selector_20180730.json.txt」ですが、インポートに失敗するのはどこに失敗があるのでしょうか？（指示通りに変更はしたのですが）

よろしくお願い致します。

**Comment by zel3** [comment]
インポートに失敗するのですがどうすればいいでしょうか？

**Comment by bokodeko** [comment]
失礼します。

先程(再度)手順通りやってみましたら、読み込み成功→pixivの方、(まだ一点だけですが)普通にDLできました。

※"datetime": {"s": "figcaption div[title="投稿日時"]"},
　"datetime": {"s": "figcaption div[title=\"投稿日時\"]"},→「\」を忘れておりました。

分析された「kayamaiさん」と、手順を示された「enoki5150さん」には感謝を。

あと「保存済み/使用済み」が表示され(て)ない…のかも。

**Comment by bokodeko** [comment]
失礼します。

先程(再度)手順通りやってみましたら、読み込み成功→pixivの方、(まだ一点だけですが)普通にDLできました。

※"datetime": {"s": "figcaption div[title="投稿日時"]"},
　"datetime": {"s": "figcaption div[title=\"投稿日時\"]"},→「\」を忘れておりました。

分析された「kayamaiさん」と、手順を示された「enoki5150さん」には感謝を。

あと「保存済み/使用済み」が表示され(て)ない…のかも。

**Comment by bokodeko** [comment]
失礼します。

先程(再度)手順通りやってみましたら、読み込み成功→pixivの方、(まだ一点だけですが)普通にDLできました。

※"datetime": {"s": "figcaption div[title="投稿日時"]"},の部分に関しましては、kayamaiさんが分析したものをコピーしました。→「\」が掲示板書き込みでは消えるみたいで。

分析された「kayamaiさん」と、手順を示された「enoki5150さん」には感謝を。

あと「保存済み/使用済み」が表示され(て)ない…のかも。

**Comment by zel3** [comment]
成功しましたありがとうございます

**Comment by bokodeko** [comment]
数点保存してみてですが…

typetonk2さんが暫定的に7月18日に置かれた物の時もそうでしたが「保存済み/使用済み」が表示されなかった…と記憶します。

今回もそのような状況にあるようで、その修正等はボチボチ…ということで。（以下、全くの素人考えです。その辺りをちょくちょく運営は弄ってるのでしょうか…ね？）

**Comment by bokodeko** [comment]
数点保存してみてですが…

typetonk2さんが暫定的に7月18日に置かれた物の時もそうでしたが「保存済み/使用済み」が表示されなかった…と記憶します。

今回もそのような状況※にあるようで、その修正等はボチボチ…ということで。（以下、全くの素人考えです。その辺りをちょくちょく運営は弄ってるのでしょうか…ね？）

※保存中の表示（情報取得中、失敗…等々）

**Comment by enoki5150** [comment]
>※"datetime": {"s": "figcaption div[title="投稿日時"]"},の部分に関しましては、kayamaiさんが分析したものをコピーしました。→「\」が掲示板書き込みでは消えるみたいで。

bokodekoさん訂正ありがとうございます。そこは気づきませんでした。
画像一覧の保存済みは出ますし、保存した画像は警告画面が出るのでさほど不便には思ってません。
とにかくまた保存できるようになってよかった。

**Comment by LucionGid** [comment]
@enoki5150 I have done exactly as you said (including saving the override_selector with UTF-8 without signature encoding), but got the error [Failed] import override selector configuration.

**Comment by LucionGid** [comment]
@usr7072 Thank you for uploading the file. However, although i can import your override_selector, i still get the error "cannot find images" when trying to DL. Maybe pixiv changes again?

**Comment by usr7072** [comment]
This is because it is supposed to be used in a Japanese environment.
I tried creating it in English environment so please use it.
`unofficial_override_selector_20180812_eng.json`

**Comment by LucionGid** [comment]
@usr7072 thank you, after importing the updated override_selector, i was able to DL again. I hope that we get an official fix for this, as the usual "already downloaded" notification is missing. The downloaded images themselves are still marked with a different color so it's less of a problem right now, though.

**Comment by usr7072** [comment]
@LucionGid As for the message display such as "already downloaded", I solved it just before importing again.

downloadedDisplayParentが保存済みや失敗表示のセレクタになってたのでそっちも弄りました。
自分の方でDLしまくってテストしましたが今まで通り動いている気がします。

**Comment by chyuaner** [comment]
@usr7072 How to use your unofficial-override-selector repo?

**Comment by usr7072** [comment]
@chyuaner
Is there an item such as "selector import" on the setting screen of AnkPixiv? You can open the downloaded json there.

Currently "unofficial override selector" is the latest.

**Comment by enoki5150** [comment]
複数枚の画像はダウンロードできるのに１枚のイラストはダウンロードできなくなりましたね

**Comment by bokodeko** [comment]
enoki5150さんご指摘の通り「一枚イラスト」はダウンロードできなくなっています。
（以前のように「画像を見つけられませんでした」とはならず、「情報取得中」から先に進まない状態です）

いつも申し訳ありませんが、対応をよろしくお願い致します。

**Comment by enoki5150** [comment]
うごイラもダウンロードできますね
なぜ一枚絵だけ？

**Comment by usr7072** [comment]
[ビュアー]
中サイズ画像をクリックで、同一タブに大サイズ画像を表示する 

これが有効だと拡大表示出来ないあたり、画像URLに関する情報がそもそも取れていないようなそんな感じですかね？
セレクターは色々弄ってみたけど問題無い気がする・・・？自分の弄り方が悪いだけかもですが。

開発勉強中の自分はここでお手上げです(´・ω・｀)

一応ログをば。
not manga: illustType = 0        pixiv.js:370:13  
getMangaPath moz-extension://dc2d24f7-e2a3-4c5c-9351-2a47cb03df47/js/sites/pixiv.js:370:13  
undefined                        site.js:613:23  
downloadCurrentImage/< moz-extension://dc2d24f7-e2a3-4c5c-9351-2a47cb03df47/js/site.js:613:23  
skip mark downloaded            site.js:917:13

**Comment by bokodeko** [comment]
失礼します。
現段階でも継続中の模様ですが、これは…「設定上の問題(各自PCの問題含む)」でしょうか？それとも、所謂「(ここしばらくpixiv側の変更等)環境変化による問題」になるのでしょうか？

**Comment by enoki5150** [comment]
仕様変更の方みたいですね、みんな同じ症状みたいだし

**Comment by ginzu** [comment]
3.0.12で一区切りついたと判断し、closeとします。

**Comment by usr7072** [comment]
ダウンロード可能になりました。ご対応ありがとうございます。

**Comment by pekeko** [comment]
61.0.2 firefoxで一枚絵ダウンロード確認できました。
うごイラは未確認です。
お忙しいなかいつも迅速なご対応ありがとうございます！
