### ISSUE TITLE
特定ユーザーのイラストのダウンロードに失敗する

### ISSUE THREAD

**Issue by eulpnu** [anekos/Ank-Pixiv-Tool#175]
特定ユーザーのイラストのダウンロードに失敗します
https://www.pixiv.net/member_illust.php?id=2388729
ログを取る時に使ったイラスト
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68704426
Ank Pixiv Tool 3.0.6
Firefox Developer Edition 62.0b1 
ファイル名は「AnkPixiv/?site-name?/?memoized-name?(?member-id?)/?memoized-name?(?member-id?)(?member-name? - ?pixiv-id?) - ?title?(?illust-id?)?site-name?」に設定しています。
自分の環境では両方の?memoized-name?を削った場合は保存ができました。
失敗ログ
<details>
SITE MODULE INSTALLED: PXV https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68704426 site.js:89:7
wait for retry: 1 / 30 : middleClickEventFunc utils.js:515:9
wait for retry: 1 / 30 : delayDisplaying utils.js:515:9
wait for retry: 1 / 30 : delayMarking utils.js:515:9
installed: openCaption utils.js:510:9
installed: niceEventFunc utils.js:510:9
wait for retry: 1 / 30 : detectContentChange utils.js:515:9
wait for retry: 1 / 30 : followExpansion utils.js:515:9
wait for retry: 1 / 30 : recommendExpansion utils.js:515:9
installed: middleClickEventFunc utils.js:510:9
wait for retry: 2 / 30 : delayDisplaying utils.js:515:9
wait for retry: 2 / 30 : delayMarking utils.js:515:9
wait for retry: 2 / 30 : detectContentChange utils.js:515:9
wait for retry: 2 / 30 : followExpansion utils.js:515:9
installed: recommendExpansion utils.js:510:9
CONTEXT:  
Object { downloadable: true, service_id: "PXV", siteName: "Pixiv", path: {…}, info: {…} }
site.js:566:7
installed: delayDisplaying utils.js:510:9
installed: delayMarking utils.js:510:9
installed: detectContentChange utils.js:510:9
wait for retry: 3 / 30 : followExpansion utils.js:515:9
/\?memor?ized-name\?/g is not found site.js:217:13
skip mark downloaded site.js:887:13
wait for retry: 4 / 30 : followExpansion utils.js:515:9
wait for retry: 5 / 30 : followExpansion utils.js:515:9
wait for retry: 6 / 30 : followExpansion utils.js:515:9
wait for retry: 7 / 30 : followExpansion utils.js:515:9
wait for retry: 8 / 30 : followExpansion utils.js:515:9
wait for retry: 9 / 30 : followExpansion utils.js:515:9
wait for retry: 10 / 30 : followExpansion utils.js:515:9
wait for retry: 11 / 30 : followExpansion utils.js:515:9
wait for retry: 12 / 30 : followExpansion utils.js:515:9
wait for retry: 13 / 30 : followExpansion utils.js:515:9
wait for retry: 14 / 30 : followExpansion utils.js:515:9
wait for retry: 15 / 30 : followExpansion utils.js:515:9
wait for retry: 16 / 30 : followExpansion utils.js:515:9
wait for retry: 17 / 30 : followExpansion utils.js:515:9
wait for retry: 18 / 30 : followExpansion utils.js:515:9
wait for retry: 19 / 30 : followExpansion utils.js:515:9
wait for retry: 20 / 30 : followExpansion utils.js:515:9
wait for retry: 21 / 30 : followExpansion utils.js:515:9
wait for retry: 22 / 30 : followExpansion utils.js:515:9
wait for retry: 23 / 30 : followExpansion utils.js:515:9
wait for retry: 24 / 30 : followExpansion utils.js:515:9
wait for retry: 25 / 30 : followExpansion utils.js:515:9
wait for retry: 26 / 30 : followExpansion utils.js:515:9
wait for retry: 27 / 30 : followExpansion utils.js:515:9
wait for retry: 28 / 30 : followExpansion utils.js:515:9
wait for retry: 29 / 30 : followExpansion utils.js:515:9
wait for retry: 30 / 30 : followExpansion utils.js:515:9
Error: "retry over:"
delayFunctionInstallermoz-extension://b27b4cbf-6917-47b2-9bda-6bf701b1212f/js/utils.js:520:27 pixiv.js:882:21
skip mark downloaded site.js:887:13
skip mark downloaded site.js:887:13 
</details>

memoizedを削った成功ログ
(ファイル名「AnkPixiv/?site-name?/(?member-id?)/(?member-id?)(?member-name? - ?pixiv-id?) - ?title?(?illust-id?)?site-name?」)
<details>
SITE MODULE INSTALLED: PXV https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68704426 site.js:89:7
wait for retry: 1 / 30 : middleClickEventFunc utils.js:515:9
wait for retry: 1 / 30 : delayDisplaying utils.js:515:9
wait for retry: 1 / 30 : delayMarking utils.js:515:9
installed: openCaption utils.js:510:9
installed: niceEventFunc utils.js:510:9
wait for retry: 1 / 30 : detectContentChange utils.js:515:9
wait for retry: 1 / 30 : followExpansion utils.js:515:9
wait for retry: 1 / 30 : recommendExpansion utils.js:515:9
installed: middleClickEventFunc utils.js:510:9
wait for retry: 2 / 30 : delayDisplaying utils.js:515:9
wait for retry: 2 / 30 : delayMarking utils.js:515:9
wait for retry: 2 / 30 : detectContentChange utils.js:515:9
wait for retry: 2 / 30 : followExpansion utils.js:515:9
installed: recommendExpansion utils.js:510:9
wait for retry: 3 / 30 : delayDisplaying utils.js:515:9
wait for retry: 3 / 30 : delayMarking utils.js:515:9
wait for retry: 3 / 30 : detectContentChange utils.js:515:9
wait for retry: 3 / 30 : followExpansion utils.js:515:9
installed: delayDisplaying utils.js:510:9
installed: delayMarking utils.js:510:9
installed: detectContentChange utils.js:510:9
wait for retry: 4 / 30 : followExpansion utils.js:515:9
wait for retry: 5 / 30 : followExpansion utils.js:515:9
wait for retry: 6 / 30 : followExpansion utils.js:515:9
wait for retry: 7 / 30 : followExpansion utils.js:515:9
wait for retry: 8 / 30 : followExpansion utils.js:515:9
wait for retry: 9 / 30 : followExpansion utils.js:515:9
wait for retry: 10 / 30 : followExpansion utils.js:515:9
wait for retry: 11 / 30 : followExpansion utils.js:515:9
wait for retry: 12 / 30 : followExpansion utils.js:515:9
wait for retry: 13 / 30 : followExpansion utils.js:515:9
wait for retry: 14 / 30 : followExpansion utils.js:515:9
wait for retry: 15 / 30 : followExpansion utils.js:515:9
wait for retry: 16 / 30 : followExpansion utils.js:515:9
wait for retry: 17 / 30 : followExpansion utils.js:515:9
wait for retry: 18 / 30 : followExpansion utils.js:515:9
wait for retry: 19 / 30 : followExpansion utils.js:515:9
wait for retry: 20 / 30 : followExpansion utils.js:515:9
wait for retry: 21 / 30 : followExpansion utils.js:515:9
wait for retry: 22 / 30 : followExpansion utils.js:515:9
wait for retry: 23 / 30 : followExpansion utils.js:515:9
wait for retry: 24 / 30 : followExpansion utils.js:515:9
wait for retry: 25 / 30 : followExpansion utils.js:515:9
wait for retry: 26 / 30 : followExpansion utils.js:515:9
wait for retry: 27 / 30 : followExpansion utils.js:515:9
wait for retry: 28 / 30 : followExpansion utils.js:515:9
wait for retry: 29 / 30 : followExpansion utils.js:515:9
wait for retry: 30 / 30 : followExpansion utils.js:515:9
Error: "retry over:"
delayFunctionInstallermoz-extension://b27b4cbf-6917-47b2-9bda-6bf701b1212f/js/utils.js:520:27 pixiv.js:882:21
CONTEXT:  
Object { downloadable: true, service_id: "PXV", siteName: "Pixiv", path: {…}, info: {…} }
site.js:566:7
/\?memor?ized-name\?/g is not found
site.js:217:13
skip mark downloaded
</details>
ログは出し方がいまいちよくわからなかったので、わからないなりにコンソールをコピーしてきたのですが至らない点ありましたら指摘していただければまたやってみます。

**Comment by ginzu** [comment]
こんな内容のバグでした。

* 2.xで履歴をエクスポート→3.xで履歴をインポートする
* memoized_nameが数字のみのアカウントの場合、文字列(memoized_name="2")ではなく数値(memoized_name=2)として取り込まれる
* ファイル名生成の際にmemoized_name.replace()を呼び出すが、文字列ではなく数値なのでそんなメソッドはないよ例外が発生して処理が中断される
* 3.xになってから新たに登録されたユーザではこの問題は発生しない

修正したものをcommitしたので試してみてください。

**Comment by eulpnu** [comment]
無事動作しました！
迅速に対応していただいてありがとうございました。
