### ISSUE TITLE
Nijie.info has MP4 now

### ISSUE THREAD

**Issue by QuessParaya** [anekos/Ank-Pixiv-Tool#179]
Nijie.info how supports MP4 files.

https://nijie.info/search.php?word=MP4

When trying to download, it says "Cannot find images!".

**Comment by ginzu** [comment]
please try it > [override_selector_20180731.json.txt](https://github.com/anekos/Ank-Pixiv-Tool/files/2245604/override_selector_20180731.json.txt)

**Comment by QuessParaya** [comment]
It works now. Thanks!
