### ISSUE TITLE
Twitterの画像保存について

### ISSUE THREAD

**Issue by Drat57** [anekos/Ank-Pixiv-Tool#180]
Twitterの画像を保存しようとするとダウンロード中と出てそのままタイムアウトで
ダウンロード失敗となってしまうようです

Firefox61.01(64bit)
Ank Pixiv Tool 3.0.10

**Comment by ginzu** [comment]
開発環境ではダウンロードが成功し、再現できませんでした。

**Comment by Drat57** [comment]
すみません、色々試してみて駄目だったのですが
試しにChromeに入れてみたら問題なく動いたので
自分の環境の問題のようです

この度はお手間を取らせて申し訳ございません
