### ISSUE TITLE
ank-pixiv-tool.snca.net について

### ISSUE THREAD

**Issue by anekos** [anekos/Ank-Pixiv-Tool#193]
Wiki https://github.com/anekos/Ank-Pixiv-Tool/wiki/%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB において ank-pixiv-tool.snca.net へ言及があります。

これって、前から動いてないものと認識いましたが、違ったでしょうか。
また、必要性についても伺いたいです。
必要なら、別の方法でやろうかと思います。

**Comment by anekos** [comment]
現状をちゃんと認識できてなくてすみません…。

**Comment by ginzu** [comment]
wikiに書いていることのほとんどは、XUL版時代によく聞かれた質問をまとめたようなもので、今となっては不要な情報ばかりなので、まとめて削除しておきます。

**Comment by anekos** [comment]
了解です。
ありがとうございます。
