### ISSUE TITLE
Unable to download picture on the Twitter in new UI

### ISSUE THREAD

**Issue by SWN-002** [anekos/Ank-Pixiv-Tool#195]
Today, Twitter has changed to their new style and no more old style.
At the same time, Ank pixiv tool is malfunction.

Ank Pixiv Tool Version is 3.0.12
With Firefox 69.0 64bit on Mac OS 10.14.5
(Same thing on the same version of FireFox on Windows 10 1903)

**Comment by gogo831214** [comment]
you can use this"https://addons.mozilla.org/zh-TW/firefox/addon/goodtwitter/" back to old UI

**Comment by SWN-002** [comment]
> you can use this"https://addons.mozilla.org/zh-TW/firefox/addon/goodtwitter/" back to old UI

Well...
I got the other one: "https://addons.mozilla.org/en-US/firefox/addon/fix-my-twitter/"
