### ISSUE TITLE
【要望】DL済みの画像を評価する時のオプション（Feature Request: Options for giving a score rating if the illustration was already downloaded）

### ISSUE THREAD

**Issue by winiah** [anekos/Ank-Pixiv-Tool#68]
2.0.1 リリース乙です〜
いつも Ank を愛用しています、
anekos さんも ginzu さんも愛してます

さて、自分は普段採点同時に DL してるので、あんまり Ank アイコンを押してなかったんだが、さっき逆の手順を取ったら（採点が後となって）、ダウンロードしなければ、採点もできなくなってるらしい

※注：「confirmExistingDownloadWhenAuto」を無効にすればダイアログは出ない、が、「保存済み」の文字も一時的に消える

こういう場合に、再 DL の確認同時に、「採点のみを行う」のオプションも付いた方がいいと思います

では、よろしくお願い致します

（あと zh-TW ロケールを Babelzilla にうｐしました、そちらもよろ〜）

**Comment by ginzu** [comment]
ダウンロード済みのページに対して中画像クリック or 評価イベントが発生してもダウンロード処理を行わないようにしました（webextension版）。
https://github.com/anekos/Ank-Pixiv-Tool/blob/9ed28933014a098c35ae236ef53c2d85b801e11a/webextensions/source/js/site.js#L282-L295
