### ISSUE TITLE
「ダウンロード失敗！」などと出る

### ISSUE THREAD

**Issue by kahusi** [anekos/Ank-Pixiv-Tool#69]
例事URI
http://www.pixiv.net/member_illust.php?mode=medium&illust_id=47141879
http://www.pixiv.net/member_illust.php?mode=medium&illust_id=47144125
「ダウンロード中」と暫く出た後、
「ダウンロード失敗！
Status: 206」なるダイアログが出る。
ものに據ってはダウンロード出來るので或はサーヴァが惡いのかもしれないが報告しておきます。

**Comment by ginzu** [comment]
凄い今更の話で申し訳ないのですが、200ではなく206が返って来るけど、送られてきたバイト数を調べると別段分割されていないというものが頻発していた時期があって、それに対応した修正を入れています＞ 89388bd
