### ISSUE TITLE
TypeError While Downloading Single Image

### ISSUE THREAD

**Issue by nekoshota** [anekos/Ank-Pixiv-Tool#74]
TypeError when downloading single image. Maybe just me?

<<ANK<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[TypeError]
  message: path.image.images[0] is undefined
  filename: chrome://ankpixiv/content/sites/ankpixiv.js
  linenumber: 334
  stack: AnkModule/path.ext@chrome://ankpixiv/content/sites/ankpixiv.js:334
AnkContext@chrome://ankpixiv/content/ankcontext.js:114
AnkBase.downloadCurrentImage@chrome://ankpixiv/content/ankbase.js:724
AnkBase.onDownloadButtonClick@chrome://ankpixiv/content/ankbase.js:2030
onclick@chrome://browser/content/browser.xul:1

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by Sodazer0** [comment]
Thank you very much d-dd
Your recipe worked perfekt on the first try.

Now everthing works again. 
Thank you so much

**Comment by nekoshota** [comment]
@d-dd << I have tried your solution and it has worked perfectly. Thank you!
