### ISSUE TITLE
Ank Pixiv Tools don't work at all

### ISSUE THREAD

**Issue by rhea4765** [anekos/Ank-Pixiv-Tool#78]
I'm using the latest ank pixiv tools (2.0.1) on firefox 35.0 and it doesn't work. the icon tools don't do anything, and even when I use it from tools->download current pixiv image it doesn't work too. any help?

**Comment by LucionGid** [comment]
I have the same problem with firefox 35.0 and I have rolled back to 34 just to use this addon, that's how this addon important to me. Hope you guy will fix this problem :)
https://support.mozilla.org/en-US/kb/install-older-version-of-firefox
Guess now I will stick with firefox 34 until an update for ank pixiv is available

**Comment by rhea4765** [comment]
alrighty then, thank you!
