### ISSUE TITLE
can't download and can't show the downloading history(20150117)

### ISSUE THREAD

**Issue by loyuli** [anekos/Ank-Pixiv-Tool#79]
today i find this problem
and i can't use the bottom to go to pixiv either
how fix this error?

thanks

**Comment by ginzu** [comment]
If the Firefox version is 35.0,
try [fix/does_not_work_in_firefox37](https://github.com/anekos/Ank-Pixiv-Tool/compare/fix/does_not_work_in_firefox37) branch or later.

**Comment by loyuli** [comment]
it was fixed,
thank you very much!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
