### ISSUE TITLE
署名必須化について

### ISSUE THREAD

**Issue by anekos** [anekos/Ank-Pixiv-Tool#80]
[Latest topics > Firefox 41以降での、アドオンの署名義務化の影響について - outsider reflex](http://piro.sakura.ne.jp/latest/blosxom/mozilla/xul/2015-02-12_signed.htm)

**Comment by anekos** [comment]
更新が頻繁になると困るかも。

**Comment by ginzu** [comment]
一番影響を受けるのはこないだ出来た自動ビルドのページでしょうか。
ankpixivに限らない話ですが、無署名xpi使うために古いfirefoxを使い続ける、というような事態が発生するのは避けたいですね…。

**Comment by anekos** [comment]
開発者用のであれば良いようですが、それを一般に勧めのもどうかって感じですしね。

**Comment by anekos** [comment]
(ちゃんと読めていないのであやしいですが)28日にアップロードしてあるのを署名するよ、みたいなメールがきていました。

**Comment by anekos** [comment]
AMO のはなしです。

**Comment by ginzu** [comment]
以前リリース方法についてどうするかという話がちょっとだけ出ましたが、
署名必須化がいよいよ近づいてきたという事で、
どんな感じがベターでしょうか。

* AMOでの公開を続ける(この場合ginzuも開発者登録してお手伝い)
* AMOから消してここでの公開のみにする
* その他

**Comment by enoki5150** [comment]
署名化のことでしょうが2.0.1.1-signedにアップデートしたらpixivの画像が保存できなくなりました
2.0.1に戻したらまた保存できるようになりました
Firefoxは38.01
OSはwin7 PROです

**Comment by ginzu** [comment]
開発者登録が完了しwebextension版のリリースにも成功しましたのでcloseとさせていただきます。
