### ISSUE TITLE
[bug] version 2.0.1.1-signed (Fx 38.0.1)

### ISSUE THREAD

**Issue by winiah** [anekos/Ank-Pixiv-Tool#83]
更新したら使えなくなる（DL可能なページにはアイコンは青色になるけどそれ以外は機能しない）

----
After updating, it will be unusable. (In a page which can be DL, the icon will be blue, but outside of that, it wouldn't work anymore)

**Comment by enoki5150** [comment]
とりあえず2.0.1に戻せば保存できるようになりますよ

**Comment by Baniita** [comment]
Sorry, I don't quite understand. After updating to the fix, it won't work anymore..? Or do you mean after Pixiv updated..?

**Comment by ginzu** [comment]
2.0.1.1-signedは2.0.1と同じものです。
mozzilaが2.0.1に署名を付けました。
Firefox35.0以降では2.0.1は動作しません。
最新のブランチを試してみてください。

---

2.0.1.1-signed is same as 2.0.1.
Mozzila added a signature to 2.0.1.
2.0.1 does not work with FF35.0 or later.
Please try latest branch.

**Comment by enoki5150** [comment]
2.1.0にアップデートしたら動作は問題ないのですがアイコンの上にバツマークがつくようになりましたがこれは何なんでしょうか？
pixivや画像のページを表示してもマークが付いたままなんですが…
Firefoxは38.0.5です

**Comment by ginzu** [comment]
enoki5150さま

当該issueとは別の話題になるものは、個別のissueの作成をお願いします。
今回の場合、ここは2.0.1.1-signedのissueですので、2.1.0についての話題は別件です。

**Comment by Baniita** [comment]
Pardon, which latest branch? o ~o)" All the ones I see are 4+ years old. Sorry for my nubbishness.

**Comment by heijisan** [comment]
2.0.1.1に更新されるとダウンロードできなくなります。
Firefoxは38.0.5使用していますが2.0.1の時は正常にダウンロードできていました。
2.0.1.1から2.0.1に戻すと正常に使用できます。
とりあえず戻して使用していますが何故でしょう？

あと掲題とは外れますが、マンガ保存時のサブフォルダ作成に関する設定で
サブフォルダ内のファイル名ページ番号以外に作者名やイラストタイトルを
追加したい場合はどのように設定すればいいのでしょうか？
素人質問であれですが、どなたか教えていただけると嬉しいです。

**Comment by Artan1408** [comment]
@Baniita 
did you figure out how to fix this? how to use latest branch?  (assuming you're having the same problem as me and can't download anymore?)

**Comment by Baniita** [comment]
@Artan1408 Nope. ;c I still can't download.

**Comment by d-dd** [comment]
@Baniita @Artan1408 Did you try downloading the xpi linked here? https://github.com/anekos/Ank-Pixiv-Tool/wiki/インストール#自動ビルドサイトからインストール

**Comment by Baniita** [comment]
@d-dd That was last updated in April. o -o I don't think that's going to work with the latest Firefox.

**Comment by d-dd** [comment]
@Baniita Why do you think that?

**Comment by Artan1408** [comment]
@d-dd the problem started with the new FF update (about 10 days ago)

**Comment by d-dd** [comment]
@Artan1408 Which version of FF? I am assuming you are using FF38.0.x.
Note that developers often use FF Beta and Nightly to patch stuff before it gets released to FF stable (FF38 Nightly came out back in Jan...)
Unless you're also on Beta or Nightly yourself. (currently FF40/FF41).

I'm puzzled at why you won't at least try it; it only takes about 5 clicks.

**Comment by Artan1408** [comment]
@d-dd I'm using 38.0.5 and didn't have any problems until a few days ago.
I don't know if it's relevant but some of the extensions (including Ank Pixiv) now have this " -singed " attached to their names. (I don't know what it means)
I downloaded the zip file (Ank pixiv tool master) I can't read Japanese but I understood I should change the zip to xpi? and where should I put the xpi file? ( I have 3 ankpixiv@snca.net.xpi in my ff profile) sorry if it's a silly question!
I just don't want to lose my download history/options  ^^;
