### ISSUE TITLE
thx for the 2.1.0 update

### ISSUE THREAD

**Issue by k24768** [anekos/Ank-Pixiv-Tool#86]
I tried it with fx v38, and it worked fine.
But for some reasons, I'd like to keep in older fx.
Could you make ank pixiv tool compatible with older fx just like previous versions?

**Comment by ginzu** [comment]
2.1.0ではFirefox37.0以降でしか正常に動作しないAPIを利用しています。
それを使わないようにするのは難しいです。
すみません。

---

In 2.1.0, I'm using API that works in Firefox37 or later.
It is difficult to avoid using it.
Sorry.

**Comment by k24768** [comment]
Thank you for the reply. I will try to fix the migrating problems.
