### ISSUE TITLE
PNG in manga converted to JPG

### ISSUE THREAD

**Issue by blms** [anekos/Ank-Pixiv-Tool#88]
I've noticed lately that PNG files in a manga will always be saved as JPG. This wasn't always the case.

For example, the following two mangas by やとすけ are made up of only PNG images. However, when I try to save them now I only get JPG format images. (NSFW for reference: [ついったに上げたやつ](http://www.pixiv.net/member_illust.php?mode=medium&illust_id=45132818) and [デブシャチ獣人](http://www.pixiv.net/member_illust.php?mode=medium&illust_id=44679907))

![Screenshot](https://cloud.githubusercontent.com/assets/7234006/8173614/4e8d7034-139e-11e5-92d3-65a2f7509b19.png)

**Comment by d-dd** [comment]
Is the last checkmark in options is checked?

**Comment by psybustermk2** [comment]
@blms Whoa those links have content I didn't expect. Perhaps a mark next time, like nsfw? :sweat_smile:

**Comment by blms** [comment]
@d-dd Wow, completely missed that. That was it. Thanks!
@psybustermk2 Oops, sorry about that.
