### ISSUE TITLE
Wrong download issue

### ISSUE THREAD

**Issue by LucionGid** [anekos/Ank-Pixiv-Tool#89]
I'm using Ank pixiv with FF 38.0.1
The wrong download issue is like this:
- Tab 1: A pixiv picture
- Tab 2: A pixiv manga

If I click on ank pixiv icon to download picture in tab 1, but before the "wait for start" appear, i quickly use ctrl + tab to switch to tab 2. Then when the download process for tab 1 starts, it will download the manga in tab 2 with folder name of picture in tab 1 (without extension like jpg, png... of course). Pixiv picture in tab 1 will become "Already downloaded", and re-download this picture still download the manga in tab 2.

**Comment by ginzu** [comment]
今は直ってる…はず。
