### ISSUE TITLE
[バグ]アイコンが「×」になる／[BUG] X icon is displayed. (2.1.0)

### ISSUE THREAD

**Issue by ginzu** [anekos/Ank-Pixiv-Tool#90]
DBの初期化が正常に終了したら「×」アイコンから通常アイコンに変更するようになっているが、
ツールバーの準備が整ってなくてアイコン変更ができずに初期化処理が終了する場合があるものと思われる（確認はしていない）。

アイコン画像以外には影響がないので、対応未定。

**Comment by enoki5150** [comment]
うちの場合は逆に今までアイコンに「×」がついていたのにFirefoxが40にアップデートしたら消えました。
(Classic Theme Restorerを入れていた関係でしょうか？)
署名の問題でMozillaから改めてインストールしたのもあるんでしょうか？

**Comment by winiah** [comment]
http://i.imgur.com/CNeFuWW.png

プライベートブラウジングでは正しいけどね、原因不明

**Comment by enoki5150** [comment]
追記
40.02にアップデートしたらまた☓が付くようになりました

**Comment by ginzu** [comment]
fixed 3eaff81
