### ISSUE TITLE
複数枚投稿が保存できない

### ISSUE THREAD

**Issue by enoki5150** [anekos/Ank-Pixiv-Tool#92]
なぜかこのイラストが保存できません
ank pixiv toolは2.1.0　Firefox 39.0.3　OSはWin7PROです
http://www.pixiv.net/member_illust.php?mode=medium&illust_id=51867496

**Comment by enoki5150** [comment]
自己解決しました。なぜかFirefoxが40になると保存できるようになりました。
署名の問題でMozillaから改めてインストールしたのもあるんでしょうか？

**Comment by vvssxxx** [comment]
Greetings,
Previously I use "ank_pixiv_tool__master__2015-04-18_13-55-41.xpi" for downloding manga;
It could not work from 9/24.
I changed to ank pixiv tool 2.1.0, and manga could not be download.
Please share you method to solve this issue.
Thanks

ank pixiv tool-2.1.0
Firefox-41
OS-Win7 PRO 64bit
