### ISSUE TITLE
Twitterの画像を取得できない場合がある

### ISSUE THREAD

**Issue by Tommbrera** [anekos/Ank-Pixiv-Tool#94]
Firefox41.0に更新されたあたりのタイミングで（明確な原因は不明）、
Twitterのタイムライン上の投稿画像のダウンロードができなくなりました。
適当な画像を落とそうとしたときのエラー表示を以下に添付します。

<2015-09-27-1828 追記>
ある画像つきツイートのツイート単体のURLを開いて、Ankアイコンをクリックすると問題なくダウンロードすることができました。
自分や他人のタイムライン上で、画像を一度クリックして画像がポップアップされた状態になった後、ポップアップ中の画像を落とそうとAnkアイコンをクリックする場合において以下のエラーが表示されて画像のダウンロードができません。

[TypeError]
  message: self.elements.illust.userName is null
  filename: chrome://ankpixiv/content/sites/anktwitter.js
  linenumber: 311
  stack: AnkPixivModule/member.id@chrome://ankpixiv/content/sites/anktwitter.js:311:11
AnkContext/self.info<@chrome://ankpixiv/content/ankcontext.js:60:11
AnkContext@chrome://ankpixiv/content/ankcontext.js:21:18
AnkPixivModule.prototype.downloadCurrentImage/<@chrome://ankpixiv/content/sites/anktwitter.js:538:23
TaskImpl_run@resource://gre/modules/Task.jsm:330:41
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:740:39

**Comment by ginzu** [comment]
こちらをどうぞ ＞ 3eaff81

**Comment by Tommbrera** [comment]
正常に動作することを確認しました。ありがとうございました。

**Comment by temydesu** [comment]
エラーメッセージは出ませんがtwitter画像を保存しようとアイコンを押すとtwitterトップページに飛ばされるようになりました

**Comment by temydesu** [comment]
閲覧機能は作動しませんでしたがtwitter本来の仕様の拡大機能？で表示される画像は保存できました
個別のURLを開いて保存しようとするとトップページに飛ばされる感じです

**Comment by ginzu** [comment]
try it > 8646c1b

@temydesu

Tommbreraさんの立てたissueは解決済みで、今回はその後に発生した別件ですので、
そのような場合は別のissueを立てて頂けるようにお願いします
(closeかlockしとけよという話でもありますが…m(_ _)m)

**Comment by temydesu** [comment]
正常に作動しました。同じtwitterでの不具合でしたのでつい続けて書き込んでしまいました。
どうもすみませんでした。ありがとうございます。
