### ISSUE TITLE
 Ank pixiv tool 2.1.0 could not download manga on pixiv since 9/24

### ISSUE THREAD

**Issue by vvssxxx** [anekos/Ank-Pixiv-Tool#95]
Greetings,
Previously, 
I used "ank_pixiv_tool__master__2015-04-18_13-55-41.xpi" for downloading manga on pixiv;
It could not work since 9/24.
I changed to ank pixiv tool 2.1.0, and manga could not be download.

New Branches doesn't work, either.
fix/twitter_gallery_has_changed
fix/new_video_element

Please help to solve this issue.
Thanks

ank pixiv tool-2.1.0
Firefox-41
OS-Win7 PRO 64bit

**Comment by ginzu** [comment]
すみません、私はその現象を再現できませんでした。
ひょっとして、サードパーティーcookieの受け入れを拒否するように設定していませんか？

---

Sorry, I have not been able to reproduce this issue.
Perhaps you've refused to accept 3rd part cookie?

**Comment by vvssxxx** [comment]
Greetings ginzu,
I checked my 3rd party cookie (was refused) and set to "accept 3rd party cookie".
ank pixiv tool works fine~

Thanks for your help.
Now I could eat & sleep well :)
