### ISSUE TITLE
[bug] Can't save TWITTER pic in version 2.1.0 (Fx 41.0.2)

### ISSUE THREAD

**Issue by winiah** [anekos/Ank-Pixiv-Tool#96]
たとえばこれ
https://twitter.com/un9man/status/649568834479783936

Ank アイコンもメニュも、DL すると、ツイッターのトップページに行ってしまうので、画像のダウンロードができなくなります。

----
When I want to download twitter pic, it will go to TWITTER's top page.

**Comment by winiah** [comment]
かなり初歩的なトライ＆エラーだが、どうやらツイッター側の仕様変更が原因らしいので、v2.0.1.1 では全然動作してくれない

----
guessing 'cause TWITTER changed something, so it can't work in v2.0.1.1 too.

**Comment by ginzu** [comment]
already fixed
see #94

**Comment by winiah** [comment]
3eaff81
8646c1b

両方適用してみると無事に直りました、アップデートの方もよろしくお願い致します。どうもありがとうございます
