### ISSUE TITLE
「ダウンロード履歴を保存する」のチェックを外すと、ダウロード間隔が長くなる

### ISSUE THREAD

**Issue by otsdzephyr** [anekos/Ank-Pixiv-Tool#97]
設定で「ダウンロード履歴を保存する」のチェックを外すと、ダウロード間隔が長くなります。
１枚ダウンロードして、数分何もせず、また一枚ダウンロードして数分休む。
といった感じになります。
チェックをつけると、空き時間なくダウンロードしてくれるので、回線が遅いとかそういうことではないようです。

問題が出てるのはFirefox42.0に2.1.0に 8646c1b をあてた状態でですが、症状事態はずいぶんと前から出ていました。
条件が分かったのが最近なだけで。

**Comment by ginzu** [comment]
修正しました＞ 6b7371d

**Comment by otsdzephyr** [comment]
修正確認しました。
ありがとうございました。
