### ISSUE TITLE
要望：twitterの「 画像を表示する 」の自動表示オプション

### ISSUE THREAD

**Issue by souzu** [anekos/Ank-Pixiv-Tool#98]
いつもありがたく使わせて頂いています。

表題の通りなのですが、twitterの「 画像を表示する 」というリンクがあるツイートで
画像を自動的に開いてくれるような自動表示オプションを実装して頂けたら有難いのですが。

**Comment by winiah** [comment]
あれはそのユーザーの設定で表示されないようにしておいたようで（多分エロ絵）、『Power Twitter』などのアドオンを使ってみるのが適任かもしれません…？

https://addons.mozilla.org/firefox/addon/power-twitter/

**Comment by souzu** [comment]
レスありがとうございます。
他ツールも試したこともあるのですが、異常に重かったり、大半が動かなかったりで、結局手動で開いています。
上記の『Power Twitter』も試したことありますが動かないと思います。
以外とこの機能があるアドオンって少ない印象です。
Ank-Pixiv-Tool　にこの機能があれば、動作も軽いですし嬉しいんですがひっそりと期待しておこうと思います。

**Comment by souzu** [comment]
最近のtwitter側の仕様変更で開くようになったようです
最近仕様変更が多いようで、今後どうなるのか解りませんが閉じさせて頂きます。
