### ISSUE TITLE
[要望] ImgUR アルバムの支援（Adding ImgUR in supported site）

### ISSUE THREAD

**Issue by winiah** [anekos/Ank-Pixiv-Tool#99]
たとえば（両者とも同じアルバム）
http://imgur.com/a/nWKo4/layout/grid
http://imgur.com/gallery/nWKo4

最近 ImgUR 公式提供の zip してくれダウンロードはややこしくなってきたので、Ctrl-s も ScrapBook アドオンも満足に DL できない、そこで支援してみませんか？

どうもです（ぺこり）

**Comment by ginzu** [comment]
非対応ということで。
